### ISSUE TITLE
[request?] `amplify codegen` does not reflect updated schema from local copy

### ISSUE THREAD

**Issue by sw-yx** [aws-amplify/amplify-codegen#113]
**Is your feature request related to a problem? Please describe.**

**Problem 1: codegen doesnt codegen from local copy**

when i update my local schema in `/amplify/backend/api/MYAPI/schema.graphql` and run `amplify codegen`, the generated code in `src/graphql` doesn't update at all.

we are not sure if this is a bug or working as intended. but it's clear that in order to update the generated code i have to `amplify push`.

**Problem 2: CLI gives the impression that codegen is done before push**

I have to `amplify push` before i can `codegen` the new model:

![image](https://user-images.githubusercontent.com/6764957/87955362-380bbd80-cae0-11ea-90e9-10a890cef10e.png)

this causes a LONG wait time and completely breaks my flow, for information i already have on my machine. 

**I ran `amplify push` ~~40 minutes~~ 1 hour ago and am still waiting for my updated graphql schema so i can continue working. this is not a sustainable workflow when i'm just changing one little field on my schema.**

**Repro steps**

1. `amplify add api`
2. `amplify codegen`
3. change one field in the graphql schema
4. `amplify codegen` again
5. observe that nothing has changed in `src/graphql`

**Describe the solution you'd like**

i understand you do this in order to always codegen the right thing. but perhaps offer to codegen based off my local model first, if i accept the risks of mismatch between the model i have on my machine and the model i have in the cloud.

**Describe alternatives you've considered**

do nothing

**Comment by ankitmhn** [comment]
Is there a fix or some workaround for this? I'm still facing this issue.

**Comment by nubpro** [comment]
> Is there a fix or some workaround for this? I'm still facing this issue.

https://github.com/aws-amplify/amplify-codegen/issues/113#issuecomment-795223505

**Comment by phani-srikar** [comment]
The workaround is to re-compile your updated schema as mentioned here: https://github.com/aws-amplify/amplify-codegen/issues/113#issuecomment-675165644

**Comment by Robbie-Cook** [comment]
Why in the name of all that is holy, do I need to use `amplify api gql-compile && amplify codegen` instead of just `amplify codegen` ffs

**Comment by isaac-rosterlab** [comment]
> Why in the name of all that is holy, do I need to use `amplify api gql-compile && amplify codegen` instead of just `amplify codegen` ffs

To take it one step further, why not: "amplify api gql-compile && amplify codegen && amplify codegen models" instead of just "amplify codegen". Also, this workaround should probably be entered in the docs somewhere.

**Comment by pencilcheck** [comment]
After doing all those the model which are renamed in the cloud didn't get synced to the local JS files. All models created are synced but the existing models renamed are not replaced.

**Comment by jnastaskin** [comment]
No luck for me after following these steps https://github.com/aws-amplify/amplify-codegen/issues/113#issuecomment-795223505

**Comment by cjsilva-umich** [comment]
Three and a half YEARS later and the behavior is _still_ not like the docs...

At least the mentioned workaround does the trick sometimes.

**Comment by metuuu** [comment]
I am having this issue also..

**Comment by AleksandarGT** [comment]
And what do you do if you split your graphql models into multiple files? amplify api gql-compile && amplify codegen does not work in that case. In that case I need to amplify push and only then I get codegen to work. I feel I am opening tickets regarding bad amplify behavior 3 times a week.
