### ISSUE TITLE
'BelongsTo' is generated instead of 'HasOne'

### ISSUE THREAD

**Issue by AaronZyLee** [aws-amplify/amplify-codegen#13]
**Describe the bug**
According to the[ official doc](https://docs.amplify.aws/cli/graphql-transformer/connection#has-one), a project **has one** team. After I run `amplify codegen models`, the connection part shows that project **belongs to** team instead. The output is similar across all the platforms(including iOS, Android, JS and flutter).
The schema is as following.
```GraphQL
type Project @model {
  id: ID!
  name: String
  team: Team @connection
}

type Team @model {
  id: ID!
  name: String!
}
```

Take swift modelgen as an example. The output schema for project is:
```Swift
// swiftlint:disable all
import Amplify
import Foundation

extension Project {
  // MARK: - CodingKeys 
   public enum CodingKeys: String, ModelKey {
    case id
    case name
    case team
  }
  
  public static let keys = CodingKeys.self
  //  MARK: - ModelSchema 
  
  public static let schema = defineSchema { model in
    let project = Project.keys
    
    model.pluralName = "Projects"
    
    model.fields(
      .id(),
      .field(project.name, is: .optional, ofType: .string),
      .belongsTo(project.team, is: .optional, ofType: Team.self, targetName: "projectTeamId")
    )
    }
}
```
**Amplify CLI Version**
v4.40.0

**To Reproduce**

- `amplify init` a new project and choose any frontend type
- `amplify add api` and choose graphql
-  replace the `amplify/schema.graphql` with the above schema
- run `amplify codegen models`

**Expected behavior**
The `HAS_ONE` should be generated instead of `BELONGS_TO`

**Screenshots**
None

**Desktop (please complete the following information):**
 - OS: Mac
 - Node Version: v12.18.3

**Additional context**
This is a bug for a long time and datastore implementation is based on it. One concern is that if there will be breaking changes to datastore once this is fixed.

**Comment by ruiguoamz** [comment]
This [issue](https://github.com/aws-amplify/amplify-ios/issues/1031) is somehow related to this issue

**Comment by AaronZyLee** [comment]
This will be fixed in the new relation improvement plan and v2 graqhql transformer.

**Comment by jkervine** [comment]
@AaronZyLee since I don't fully understand all the interdependencies between amplify projects/modules, does this mean that this fix will be part of this? https://github.com/aws-amplify/amplify-cli/issues/6217 ?

**Comment by AaronZyLee** [comment]
@jkervine Yes it will be definitely fixed by the new relation directives (`@belongsTo`, `hasOne` and `hasMany` instead of `@connection`)
