### ISSUE TITLE
How to validate custom created schemas?

### ISSUE THREAD

**Issue by qwe12e** [aws-amplify/amplify-codegen#144]
I'm using codegen for my angular project. It's doing a great job. I created `.graphql` files under `src/app/graphql` and define my custom queries mutations etc.

So when I update my graphql schema, I want to know if my custom created schemas are still valid.

there is a package called `eslint-plugin-graphql` this will check all the created schemas then validate it with your project `schema.graphql` However, in order for this to work, we need to put a tag in front of all generated codes.

example:
```js
const statement = gql`
  query someQuery {
    ...
  }
`
```

of course aws amplify doesn't generate like this. So perhaps we can use package called [fake-tag](https://www.npmjs.com/package/fake-tag). 

with this package we can use it like this and everything still should be working correctly.
```js
import gql from 'fake-tag'

const statement = gql`
  "A foo."
  type Foo {
    "The \`Foo\` ID."
    id: ID!
  }
`
```

**Comment by phani-srikar** [comment]
Hi @qwe12e. Thank you for bringing this to our attention. If I understand this correctly, you want to be able to validate the generated GraphQL statements along with any custom statements that you have. We do not support this currently. Will keep you posted when we have an update.
