### ISSUE TITLE
codegen adds the same files multiple times to the XCode project

### ISSUE THREAD

**Issue by albemala** [aws-amplify/amplify-codegen#190]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v12.21.0

### Amplify CLI Version

4.52.0

### What operating system are you using?

macOS 10.15.7

### Amplify Categories

auth, storage, api

### Amplify Commands

codegen, pull

### Describe the bug

When running `amplify pull` or `amplify codegen`, the appropriate Swift classes/models are correctly generated (under `amplify/generated/models`). 

The 1st problem is, these files are added (as duplicates) to the XCode project every time you run the 2 `amplify` commands above. The result is a list of warnings from XCode: 

```
Skipping duplicate build file in Copy Bundle Resources build phase: <path to project>/awsconfiguration.json
Skipping duplicate build file in Copy Bundle Resources build phase: <path to project>/amplifyconfiguration.json
Skipping duplicate build file in Copy Bundle Resources build phase: <path to project>/amplify/generated/models/<file>.swift
...
```

The 2nd problem is, these files are added to all existing XCode targets, and this causes a compile error. For example:

```
<path to project>API/API.swift:840:50: 'AccessStatus' is ambiguous for type lookup in this context
```

The problem here is that the same class is declared in multiple targets, hence the ambiguity for the compiler.

I did some research, and it looks like the problem was introduced with this recent PR: https://github.com/aws-amplify/amplify-cli/pull/6867

Before v4.51.0, model generation worked fine.

Thank you!

### Expected behavior

If the generated models/classes are already included in the XCode project, do not add them again, and do not assign them to all the existing targets.

### Reproduction steps

1. (assuming an Amplify project already exists)
2. `cd` into the iOS root project folder
3. `amplify pull`
4. `amplify codegen`
5. `amplify codegen models`

**Comment by albemala** [comment]
Thank you @josefaidt !

**Comment by diegocstn** [comment]
hey @albemala, thanks for reporting this!
I'm able to reproduce the first issue, it seems like the Xcode integration is adding the generated models and config files to wrong target, but I couldn't repro the second one.
Is `AccessStatus` a model defined in your GraphQL schema? What's the relationship between the targets in your project?

**Comment by albemala** [comment]
@diegocstn Thank you for your reply!

Yes, `AccessStatus` is an enum we define in our schema (and it was just an example to show one of the errors reported by Xcode).

The main target is `Runner`, which imports a second target called `API`:

![Screenshot 2021-07-08 at 09 37 32](https://user-images.githubusercontent.com/2332860/124890628-24e34d80-dfd0-11eb-84f1-7c8c89f259dc.png)

When I run `amplify codegen`, the generated models are added to both targets, causing the compile errors.

Fro context, in our project we have enabled both Amplify DataStore and Amplify API (using GraphQL). When I run `amplify codegen`, it generates 1 folder with all the Swift DataStore models, and 1 file called `API.swift` with all the GraphQL models/queries/mutations. Now, if I associate the Swift DataStore classes and the API.swift file with the `Runner` target only, I get a lot of compile errors. This is because they define the same classes with the same names, and Xcode gets confused. To workaround the issue, I've created a second target called `API`, and associated the API.swift file to it. So the result is:

- The `Runner` target compiles the DataStore models and imports the `API` target
- The `API` target compiles the `API.swift` file

This way I don't get any declaration conflict between DataStore and GraphQL models.

Let me know if the explanation is not clear or if you need other info. Thanks!

**Comment by diegocstn** [comment]
@albemala thanks for the details.
We've identified an issue with the Xcode integration and we're actively working on it.

On another note, I'd be curious to know how you're calling the API plugin in your project.
Are you using the generated queries/mutations symbols in API.swift or the generated Swift models as described in https://docs.amplify.aws/lib/graphqlapi/mutate-data/q/platform/ios#next-steps? In case of the latter option, you should be able to remove API.swift entirely from your project.

**Comment by albemala** [comment]
> We've identified an issue with the Xcode integration and we're actively working on it.

Thank you @diegocstn !

> On another note, I'd be curious to know how you're calling the API plugin in your project.

I'm using Amplify API/GraphQL to trigger some lambda functions, and DataStore for the database.
So unfortunately I can't get rid of API.swift (but I'd like to 😅 ).

**Comment by albemala** [comment]
I've tested the latest Amplify CLI version (5.3.0) and this issue doesn't show up any more. Thank you for working on this!
