### ISSUE TITLE
"amplify codegen models" does not recognize "external" AppSync api 

### ISSUE THREAD

**Issue by TLaue** [aws-amplify/amplify-codegen#20]
>**Note**: If your issue/bug is regarding the AWS Amplify Console service, please log it in the 
[Amplify Console GitHub Issue Tracker](https://github.com/aws-amplify/amplify-console/issues)

**Describe the bug**
"amplify codegen models" does not recognize an AppSync api which was added using "amplify add codegen --apiId ..." The command outputs: "No AppSync API configured. Please add an API"

**Amplify CLI Version**
You can use `amplify -v` to check the amplify cli version on your system
4.13.4

**To Reproduce**
1) Setup AWS AppSync api (via CFN or AWS Management Console) including a sample schema
2) Generate project via create-react-app and amplify init
3) Add api to project via "amplify add codegen --apiId ..."
4) Run "amplify codegen" -> works as expected
5) Run "amplify codegen models" -> console output: No AppSync API configured. Please add an API
6) "amplify add api"
? Please select from one of the below mentioned services: GraphQL
You already have an AppSync API in your project. Use the "amplify update api" command to update your existing AppSync API.
7) amplify update api
? Please select from one of the below mentioned services: GraphQL
The selected resource is not managed using AWS Cloudformation. Please use the AWS AppSync Console to make updates to your API

**Expected behavior**
Either the model generation (required for Amplify DataStore) is supported or a clear error message states that the model generation only works for APIs added using "amplify add api".

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Node Version. v12.14.1

**Additional context**

**Comment by AaronZyLee** [comment]
For now amplify codegen is highly coupled with cli's workflow. The comments above are a good reminder for us to reconsider the design to decouple the codegen part, especially for those amplify client SDK only users who do not use CLI for cloud formation. I mark this as an enhancement and will discuss with my teammates.

**Comment by maziarzamani** [comment]
Any update on this issue?

**Comment by alharris-at** [comment]
We are planning to work on support for externally generated AppSync APIs this year, at which point we should be able to run introspection on externally generated GraphQL endpoints, and support some of the features mentioned in this issue.

**Comment by daveharig** [comment]
+1 

CDK deployed backend here!  I have tried to create my own models that conform to Amplify Model protocol, but no luck.  

No serious dev architecture is going to deploy backend from the limited and opinionated CLI. And with the backend codebase integrated into one of the clients code base?  While all other clients try and init/add code gen or whatever other half-measure is recommended.

**Comment by seanhamstra** [comment]
+1, we need this!

**Comment by PhilippS93** [comment]
any updates?

**Comment by seanhamstra** [comment]
> We are planning to work on support for externally generated AppSync APIs this year, at which point we should be able to run introspection on externally generated GraphQL endpoints, and support some of the features mentioned in this issue.

Any updates on this? This is crucial for us!

**Comment by dpilch** [comment]
Resolved by https://github.com/aws-amplify/amplify-codegen/pull/698. Not yet released.

**Comment by dpilch** [comment]
The fix is available in the latest CLI release.
