### ISSUE TITLE
DataStore codegen wrong message for union types

### ISSUE THREAD

**Issue by drochetti** [aws-amplify/amplify-codegen#211]
**Describe the bug**
When a union type is defined in the `schema.graphql`, an attempt to generate DataStore models fails with the following message:

```
Unknown type SearchResult for field items. Did you forget to add the @model directive
```

**Amplify CLI Version**
`4.21.1`

**To Reproduce**
- Create a schema with a union type.
- run `amplify codegen models`

Sample schema:

```graphql
union SearchResult = Contact | User | Entity
type SearchableConnection {
  items: [SearchResult]
  nextToken: String
  total: Int
}
```

**Expected behavior**
A clear message stating that union types are not supported in DataStore.

**Screenshots**
*N/A*.

**Desktop (please complete the following information):**
 - OS: `MacOS 10.14.6`
 - Node Version: `12.8.0`

**Additional context**
Reported originally by @lenarmazitov: https://github.com/aws-amplify/amplify-ios/issues/544

**Comment by AndresPope** [comment]
There is an update about this topic??
