### ISSUE TITLE
Invalid DynamoDB state cannot be fixed with new schema.graphql

### ISSUE THREAD

**Issue by yuhui** [aws-amplify/amplify-codegen#220]
### Before opening, please confirm:

- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-adminui/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-adminui/blob/main/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### App Id

d32bslavnn3g29

### Region

us-east-1

### Environment name

dev

### Amplify CLI Version

5.1.1

### If applicable, what version of Node.js are you using?

16.4.2

### What operating system are you using?

Mac

### Browser type?

Google Chrome

### Describe the bug

I had added a many-to-many relationship in schema.graphql, e.g. A -- AB -- B, where A and B are the main tables and AB is the join table. But this was done wrongly, such that table A did not have the required join field, though table B did. Now, when deploying the app, Amplify returns this error (actual names have been replaced with "A" and "AB"):

> A does not support 1 to 1 connection with both sides of connection as optional field: AB.fieldA

I fixed schema.graphql. But when running `amplify api push`, I still get the same error. That means Amplify is still stuck with the old schema and cannot be recovered.

Deleting the app is also not possible because of this invalid state.

### Expected behavior

When pushing a new schema.graphql, Amplify should apply the new schema and overwrite any previously set models/tables.

### Reproduction steps

1. Push an invalid schema.graphql.
2. Deploy the app and get error message.
3. Fix schema.graphql.
4. Push the updated schema.

**Comment by AaronZyLee** [comment]
There is a design defect for the current usage of `@connection` for one to one relation, where it is not allowed two connected field to be all optional. However, this is going to be resolved for the upcoming relation improvement and v2 transformer. 

Also glad to see your problem resolved. I will close this but feel free to reopen if there are any other issues
