### ISSUE TITLE
codegen models needs full backend on client

### ISSUE THREAD

**Issue by Anatoli87** [aws-amplify/amplify-codegen#222]
**Amplify CLI Version** 
5.0.1

I am working on client android app, that connects to AWS backend project

first i pull the backend to my app

```
> amplify pull --appId <appId> --envName dev
Opening link: https://us-east-1.admin.amplifyapp.com/admin/<appId>/dev/verify/
✔ Successfully received Amplify Admin tokens.
Amplify AppID found: <appId>. Amplify App name is: <appName>
Backend environment dev found in Amplify Console app: <appName>
? Choose your default editor: Android Studio
? Choose the type of app that you're building android
? Where is your Res directory:  app/src/main/res
? Do you plan on modifying this backend? No
```

Then i execute `amplify codegen`

and by `amplify codegen models` i receive an error:

>  No Amplify backend project files detected within this folder. Either initialize a new Amplify project or pull an existing project.
      - "amplify init" to initialize a new Amplify project
      - "amplify pull <app-id>" to pull your existing Amplify project. Find the <app-id> in the AWS Console or Amplify Admin UI.

When by pull of backend i select: Do you plan on modifying this backend? **Yes**
then i can generate models.
But i don't want to modify the backend.

Can i generate models without storing whole backend in client application?

We use one backend for many client apps (related ticket https://github.com/aws-amplify/amplify-cli/issues/7533)

**Comment by AaronZyLee** [comment]
The codegen depends on the graphql schema in the `amplify/` folder, which is pulled with `Yes` option. While the answer is yes literally, the backend is not really modified unless you run `amplify push`.

**Comment by Anatoli87** [comment]
@AaronZyLee , ok. But what if i want, that somebody from outside will work on frontend application forward?
I dont want share the backend with him. He should only be able to work on frontend application.
