### ISSUE TITLE
Get the introspection schema with amplify pull (without pulling the backend ressources)

### ISSUE THREAD

**Issue by alexboulay** [aws-amplify/amplify-codegen#223]
**Is your feature request related to a problem? Please describe.**
When a front-end engineer wants to use a GraphQL API, he will pull the Amplify project to access it. He does not have the intention of modifying the APIs or Functions within that Amplify project. However, he wants to use `amplify codegen` which would require to download the introspection schema from the AppSync console. Not a very nice workflow since he want's to regenerate his code as soon as there is new stuff added to the API. 

**Describe the solution you'd like**
It would be nice to be able to do `amplify codegen`, without having to download the introspection schema manually. The current solution is to pull the backend by saying "yes" when prompted by the CLI to this question "Do you plan on modifying this backend?". Maybe, another question would be, would you like to pull the introspection schema? And each subsequent pull would update the schema in question. This way, it is easy for front-end devs to keep up with the schema.

**Comment by BryceAMcDaniel** [comment]
I would request this be changed from feature-request to bug.

Currently, I am not able to get codegen to use schema.json, schema.graphql or to download and introspect by giving an appId.

Using either of the schema.json or schema.graphql that is downloaded from AppSync still requires a backend listed.

Current example and use case.
1. 'amplify pull' with choosing No for pulling amplify backend.
2. pull schema using json or SDL from aws and place in current project dir as stated above.
3. amplify codegen [statements, types, models] results in error:

`ENOENT: no such file or directory, open '[redacted]/amplify/backend/api/[project]/build/schema.graphql'`

Only after cp schema to that location does it seem to work, however, the next amplify pull erases this and it must be replaced.

**Comment by dpilch** [comment]
This can be accomplished by:
```
amplify codegen add --apiId <appsync-api-id> --region <appsync-api-region>
amplify codegen
```
