### ISSUE TITLE
Support older version of list query name

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-codegen#252]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

6.1.1

### What operating system are you using?

Mac

### Amplify Codegen Command

codegen models

### Describe the bug

Please see https://github.com/aws-amplify/amplify-cli/issues/8350

Codegen changes required
https://github.com/aws-amplify/amplify-cli/issues/8350#issuecomment-933886532

### Expected behavior

We need to have backwards compatibility with the previous way to generate a plural name for list query

`amplify codegen models` can generate schema with `listPluralName` and `syncPluralName`
```
schema
   @deprecated pluralName
   listPluralName
   syncPluralName
```

Library code can use this information if it exists, otherwise, fallback to `pluralName`
```
code
    list : graphQLName = listPluralName ?? name + "s"
    sync: graphQLName = syncPluralName ?? pluralName ?? name + "s"
```

- new developers with the feature flag enabled will model gen the schema with `listPluralName` and `syncPluralName`
- existing developers will continue to use `pluralName` for sync query and `modelName + "s”` for list query. When they upgrade, the model gen will generate only `listPluralName`  and `syncPluralName`. 

We'll need to make the change in the library first, before shipping codegen changes

iOS: https://github.com/aws-amplify/amplify-ios/blob/main/AmplifyPlugins/Core/AWSPluginsCore/Model/Support/ModelSchema%2BGraphQL.swift#L19-L22

Android: https://github.com/aws-amplify/amplify-android/blob/main/aws-api-appsync/src/main/java/com/amplifyframework/api/aws/AppSyncGraphQLRequest.java#L159-L161

### Reproduction steps

Please see https://github.com/aws-amplify/amplify-cli/issues/8350

**Comment by phani-srikar** [comment]
This is linked to the [other issue](https://github.com/aws-amplify/amplify-codegen/pull/255), can will be handled together.
