### ISSUE TITLE
Add support for passing parameter when running subscription in Angular service

### ISSUE THREAD

**Issue by Flos** [aws-amplify/amplify-codegen#26]
Since authorized subscriptions should work by now, following a few tickets aws-amplify/amplify-cli#504, aws-amplify/amplify-cli#1021, aws-amplify/amplify-cli#1766, aws-amplify/amplify-cli#1810. 
I don't understand how I can use that subscriptions now with the generated JavaScript client. How can I pass the owner to the subscription? 

```
type Todo @model @auth(rules: [{allow: owner}]){
  id: ID!
  title: String!
  owner: String
}
```

```
this.apiService.OnCreateTodoListener.subscribe((evt) => {
      console.log("added: ", evt);
});
```

**Comment by phani-srikar** [comment]
This can be handled together with #31. Closing this in favor of that.
