### ISSUE TITLE
Upgraded amplify cli, then used codegen and types where generated wrong

### ISSUE THREAD

**Issue by Leikaab** [aws-amplify/amplify-codegen#265]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.17.5

### Amplify CLI Version

6.3.1

### What operating system are you using?

Mac

### Amplify Codegen Command

codegen, codegen types

### Describe the bug

we updated the cli from a previous version (not sure which one, but think 6.0.1).
Later on we added a field to one of the models in graphql schema, this field was an optional one.
Later we ran amplify codegen to get updated code for our models.
The new field was added fine, but suddenly all the other types that had state `is required`, suddenly no longer had types as required.
Given the schema provided, par ex model Projects has this code generated:
```typescript
export type Project = {
  __typename: "Project",
  id?: string,
  title?: string,
  description?: string,
  href?: string,
  is_published?: boolean | null,
  _version?: number,
  _deleted?: boolean | null,
  _lastChangedAt?: number,
  createdAt?: string,
  updatedAt?: string,
  ImageModel?: ImageModel,
};
```

this broke our existing typescript code, since suddenly all the types where `string | undefined` instead of  `string` or `ImageModel | undefined` instead of `ImageModel`

### Expected behavior

codegen generates code that uses same types as api

### Reproduction steps

1. write graphql schema and do `amplify push`
2. `amplify pull`
3. `amplify codegen`
4. Typescript errors

### GraphQL schema(s)

<details>

```graphql
type PrivacyPolicy @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  title: String!
  subtitle: String!
  text: String!
}

type ImageModel @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  title: String
  altText: String
  src: String!
  width: String
  height: String
}

enum PlanTypeEnum {
  BASIS
  SELVSTYRT
  PRO
  ENTERPRISE
}

type Discover @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  title: String!
  ImageModel: ImageModel! @connection
}

type HomePageTitleBlock @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  mainTitle: String!
  subTitle: String!
  linkHref: String!
  firstSubtitle: String!
  secondSubtitle: String!
  ImageModel: ImageModel @connection
}

type Project @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  title: String!
  description: String!
  ImageModel: ImageModel! @connection
  href: String!
  is_published: Boolean
}

type Review @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  name: String!
  jobTitle: String!
  text: String!
  AvatarImageModel: ImageModel! @connection
}

type Logo @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  ImageModel: ImageModel! @connection
  title: String
}

type Solution @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  mainTitle: String!
  subTitle: String!
  firstSubtitle: String!
  secondSubtitle: String!
  linkHref: String!
  ImageModel: ImageModel! @connection
}

type ProsCard @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  cardTitle: String!
  cardText: String!
  planType: PlanTypeEnum!
  planDesc: String!
  ImageModel: ImageModel! @connection
}

type ServiceCard @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  cardTitle: String!
  href: String!
  ImageModel: ImageModel! @connection
}

type SolutionCard @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  cardTitle: String!
  ImageModel: ImageModel @connection
  ImageModel2: ImageModel @connection
}

type Technology @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  title: String!
  subtitle: String!
  ImageModel: ImageModel! @connection
}

type ContactCard @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  name: String!
  role: String!
  email: String!
  linkedIn: String
  phoneNumber: String!
  AvatarImageModel: ImageModel! @connection
}

type MarketingCard @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  cardTitle: String!
  cardText: String!
  ImageModel: ImageModel @connection
  BackImageModel: ImageModel @connection
}

type CollapsedListItem @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  planType: PlanTypeEnum!
  title: String!
  subtitle: String!
  description: String
  ImageModel: ImageModel @connection
  buttonText: String
  href: String
}

type GetToKnowUsList @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  text: String!
}

type Banner @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  title: String!
  subtitle: String
  type: String!
}

type S3Object {
  bucket: String!
  region: String!
  key: String!
}

type ClientApplication @model @auth(rules: [{allow: public, operations: [read]}]) {
  id: ID!
  fullName: String!
  email: String!
  phoneNumber: String
  companyName: String
  website: String
  message: String!
  file: S3Object
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}
 


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by Leikaab** [comment]
wrote here after recommendation from aws premium support

**Comment by AaronZyLee** [comment]
The previous one with all optional fields generated was a bug and fixed in this https://github.com/aws-amplify/amplify-codegen/pull/159. The current codegen behavior is to generate required type for non-nullable fields in graphql schema.

**Comment by AaronZyLee** [comment]
@Leikaab It is probably due to the outdated version/wrong feature flag.  Could you go through the following checklist so that we can figure out the reason? (if one step fails, you can just stop on that and no need to check the rest)

- [ ] `npm i -g @aws-amplify/cli` to install the latest CLI with codegen
- [ ] `amplify -v` to check the version
- [ ] `which amplify` to check the amplify from npm is installed correctly (if you have the packaged CLI installed before, you might have the wrong link to that which is outdated)
- [ ] In a fresh project, run `amplify init` then check out `amplify/cli.json` file to find the field `codegen.usetypesgeneratorplugin` to be `true`
