### ISSUE TITLE
Ability to generate different filename.swift files from directories of .graphql files

### ISSUE THREAD

**Issue by jasonbobier** [aws-amplify/amplify-codegen#28]
**Is your feature request related to a problem? Please describe.**

Yes, https://github.com/aws-amplify/amplify-cli/issues/2122

**Describe the solution you'd like**
amplify codegen --max-depth --input=MySubAPIDirectory --output=MySubAPIDirectory.swift

would produce an api using just the .graphql files in MySubAPIDirectory and save it as MySubAPIDirectory.swift

Basically, I don't want to create the massive namespace polluting API.swift that has everything in it. I want nice clean sub apis with just the queries, mutations, and subscriptions that I use in my app.

**Describe alternatives you've considered**
See the bug report for how I'm doing it now. It produces an error and is a hack.

**Comment by AaronZyLee** [comment]
Close this issue since this is duplicate of #39
