### ISSUE TITLE
Amplify codegen models > generating incorrect model in one to one relation [Android]

### ISSUE THREAD

**Issue by iamAliRaza** [aws-amplify/amplify-codegen#318]
**These are two simple models..
After generating Java model classes with amplify.
Previously in V1 transformation of GraphQL. Post class were taking user object.
After migrating to V2 GraphQL. Model Class generated by Amplify just taking postUserId and user object is always pointing to Null.**

Amplify CLI version : 7.5.5
NPM version : 8.1.4

```
type User @model @auth(rules: [{allow: private}]) {
  id: ID!
  email: String!
  username: String
  phoneNumber: String
  sex: String
  state: String
  city: String
  zipcode: String
  interest: String
  status: String
  userImage: String
  professions: [String]
  danceStyles: [String]
}

type Post @model @auth(rules: [{allow: private}]) {
  id: ID!
  postImage: String
  caption: String
  date: String
  startTime: String
  endTime: String
  cost: Int
  paymentLink: String
  location: String
  about: String
  likeList: [String]
  bookmarkList: [String]
  postType: PostType
  categories: [String]
  danceStyles: [String]
  addedToCalender: Boolean
  user: User @hasOne
}
```

**Comment by alharris-at** [comment]
Hi, thank you for raising this issue. We are currently working on a tagged release to address this issue, and will work with you once released to verify your issue is resolved.

**Comment by alharris-at** [comment]
Hello @iamAliRaza. We are currently verifying this release internally, but if you want to test yourself, you can pull an updated CLI build by running `npm i -g @aws-amplify/cli@codegen-gqlv2-fix` and regenerating your schema with an `amplify pull` command and verify behavior on your end.

Once verified we will be working to merge into the main CLI release.

**Comment by iamAliRaza** [comment]
Hello @alharris-at the issue is still same ... I followed exactly same steps that you mentioned...
But still the generated model is incomplete/incorrect. User Step is missing.


public interface BuildStep {
    Post build();
    BuildStep id(String id);
    BuildStep postImage(String postImage);
    BuildStep caption(String caption);
    BuildStep date(String date);
    BuildStep startTime(String startTime);
    BuildStep endTime(String endTime);
    BuildStep cost(Integer cost);
    BuildStep paymentLink(String paymentLink);
    BuildStep location(String location);
    BuildStep about(String about);
    BuildStep likeList(List<String> likeList);
    BuildStep bookmarkList(List<String> bookmarkList);
    BuildStep postType(PostType postType);
    BuildStep categories(List<String> categories);
    BuildStep danceStyles(List<String> danceStyles);
    BuildStep addedToCalender(Boolean addedToCalender);
    BuildStep postUserId(String postUserId);
  }
  
  You can check here instead of postUserId as String it should take user object...

**Comment by iamAliRaza** [comment]
@alharris-at  You can check this below interface its generated with v1 transformer and its taking user object...  

public interface BuildStep {
    Post build();
    BuildStep id(String id) throws IllegalArgumentException;
    BuildStep postImage(String postImage);
    BuildStep caption(String caption);
    BuildStep date(String date);
    BuildStep startTime(String startTime);
    BuildStep endTime(String endTime);
    BuildStep cost(Integer cost);
    BuildStep paymentLink(String paymentLink);
    BuildStep location(String location);
    BuildStep about(String about);
    BuildStep likeList(List<String> likeList);
    BuildStep bookmarkList(List<String> bookmarkList);
    BuildStep postType(PostType postType);
    BuildStep categories(List<String> categories);
    BuildStep danceStyles(List<String> danceStyles);
    BuildStep postUser(User postUser);
  }

**Comment by phani-srikar** [comment]
Please re-open if the issue still persists.
