### ISSUE TITLE
Amplify CodeGen Models handling multiple hasOne-hasMany relationships on same type incorrectly

### ISSUE THREAD

**Issue by attilah** [aws-amplify/amplify-codegen#320]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

-

### If applicable, what version of Node.js are you using?

-

### Amplify CLI Version

7.5.4

### What operating system are you using?

-

### Amplify Codegen Command

codegen models

### Describe the bug

For full context, see at: https://github.com/aws-amplify/amplify-cli/issues/9070#issuecomment-983923549

I was able to root cause it to that if a `Type` has multiple `@hasOne`, `@index`, `@hasMany` then only the first one is processed successfully as the fields with `@index` at removed from the schema under processing and `getConnectedFieldV2` will not find the other side `@index`.

This schema (original issue):

```graphql
type Meeting @model @auth(rules: [
  {allow: owner},
  {allow: groups, groups: ["Admin"]},
  {allow: public, operations: [read], provider: iam},
]) {
  id: ID! @primaryKey
  title: String!
  attendees: [Registration] @hasMany(indexName: "byMeeting", fields: ["id"]) @auth(rules: [
    {allow: owner},
    {allow: groups, groups: ["Admin"]}
  ])
}

type Attendee @model @auth(rules: [
  {allow: owner},
  {allow: groups, groups: ["Admin"]}
]) {
  id: ID! @primaryKey
  meetings: [Registration] @hasMany(indexName: "byAttendee", fields: ["id"])
}

type Registration @model(queries: null) @auth(rules: [
  {allow: owner},
  {allow: groups, groups: ["Admin"]}
]) {
  id: ID! @primaryKey
  meetingId: ID @index(name: "byMeeting", sortKeyFields: ["attendeeId"])
  meeting: Meeting! @belongsTo(fields: ["meetingId"])
  attendeeId: ID @index(name: "byAttendee", sortKeyFields: ["meetingId"])
  attendee: Attendee! @belongsTo(fields: ["attendeeId"])
}
```

Producing this error message: 
```Error processing @hasMany directive on Attendee.meetings, @index directive with name foo was not found in connected model Registration```

If I rename `Attendee` to `ZAttendee` - so it will be processed after `Meeting` then error message will be:
```Error processing @hasMany directive on Meeting.attendees, @index directive with name byMeeting was not found in connected model Registration```

### Expected behavior

Handle multiple directives for these connections correctly

### Reproduction steps

See in description

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by endoodev1** [comment]
When will we see the release of the respective PR? We have an amplify backend environment what cannot be pulled anymore as this problem leads to a breakup of amplify cli command while pulling. This is very annoying as we begin to switch to graphqlv2 and want to do new development there but we cannot move on! 
@alharris-at I saw that you published some new releases the last days. Is there a special reason why this one Is not released?

**Comment by alharris-at** [comment]
Hi @endoodev1 we are working on a release plan right now, and expect to have fixes for your issue out once we have confidence in the fix on all platforms.

**Comment by gabrielgarciagava** [comment]
@alharris-at It seems that this was released to amplify-cli yesterday on https://github.com/aws-amplify/amplify-cli/releases/tag/v7.6.9
Thank you :)
