### ISSUE TITLE
amplify codegen models generates java code that doesn't compile for requiredElementOptionalList [Android]

### ISSUE THREAD

**Issue by TimmBaier** [aws-amplify/amplify-codegen#336]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.16.1

### Amplify CLI Version

7.6.4

### What operating system are you using?

macOS 12.0.1, android 11

### Amplify Codegen Command

codegen models

### Describe the bug

This will create java code, that does't compile:
```graphql
type ListStringContainer @model {
  requiredElementRequiredList: [String!]!
  requiredElementOptionalList: [String!]
  optionalElementRequiredList: [String]!
  optionalElementOptionalList: [String]
}
```

`app/src/main/java/com/amplifyframework/datastore/generated/model/ListStringContainer.java:224: error: cannot find symbol
        .requiredElementOptionalList(requiredElementOptionalList)
        ^
  symbol:   method requiredElementOptionalList(List<String>)
  location: interface OptionalElementRequiredListStep`

### Expected behavior

I would expect it to create code that compiles, or at least throw a warning, that this is not supported on android at the moment.

### Reproduction steps

1. add a variable to any schema with an array, that is optional but the elements can't be empty (`requiredElementOptionalList: [String!]`)
2. amplify codegen models
3. try to compile your android project

### GraphQL schema(s)

<details>

```graphql
type ListStringContainer @model {
  requiredElementRequiredList: [String!]!
  requiredElementOptionalList: [String!]
  optionalElementRequiredList: [String]!
  optionalElementOptionalList: [String]
}


```

</details>

### Log output

<details>

```
/Users/user/AmplifyTest/app/src/main/java/com/amplifyframework/datastore/generated/model/ListStringContainer.java:224: error: cannot find symbol
        .requiredElementOptionalList(requiredElementOptionalList)
        ^
  symbol:   method requiredElementOptionalList(List<String>)
  location: interface OptionalElementRequiredListStep


```

</details>

**Comment by AaronZyLee** [comment]
Close due to duplicate to https://github.com/aws-amplify/amplify-codegen/issues/415
