### ISSUE TITLE
amplify codegen models producing different results in different OS(Mac and Windows).

### ISSUE THREAD

**Issue by guruken** [aws-amplify/amplify-codegen#339]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

rpm

### If applicable, what version of Node.js are you using?

16.13.1

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac

### Amplify Codegen Command

codegen models

### Describe the bug

```graphql
type SystemAdmin @model @auth(rules: [{ allow: public }]) {
  id: ID!
  systemAdminName: String
  systemAdminEmail: String
  systemAdminID: Int
}

type School @model @auth(rules: [{ allow: public }]) {
  id: ID!
  schoolName: String!
  schoolAddress: String!
  schoolFrontEndID: Int
  Teachers: [Teacher!] @hasMany(indexName: "bySchool", fields: ["id"])
  Admins: [Admin!] @hasMany(indexName: "bySchool", fields: ["id"])
  Students: [Student!] @hasMany(indexName: "bySchool", fields: ["id"])
  Courses: [Course!] @hasMany(indexName: "bySchool", fields: ["id"])
}

type Admin @model @auth(rules: [{ allow: public }]) {
  id: ID!
  adminName: String!
  adminEmail: String!
  schoolID: ID! @index(name: "bySchool")
  adminID: Int
}

type Teacher @model @auth(rules: [{ allow: public }]) {
  id: ID!
  teacherName: String!
  teacherEmail: String!
  schoolID: ID! @index(name: "bySchool")
  teacherID: Int
  courses: [Course!] @manyToMany(relationName: "TeacherCourse")
}

type Course @model @auth(rules: [{ allow: public }]) {
  id: ID!
  courseName: String!
  schoolID: ID! @index(name: "bySchool")
  students: [Student!] @manyToMany(relationName: "StudentCourse")
  assignments: [Assignment!] @hasMany(indexName: "byCourse", fields: ["id"])
  teachers: [Teacher!] @manyToMany(relationName: "TeacherCourse")
}

type Student @model @auth(rules: [{ allow: public }]) {
  id: ID!
  studentName: String
  studentEmail: String
  sisID: Int
  schoolID: ID! @index(name: "bySchool")
  courses: [Course!] @manyToMany(relationName: "StudentCourse")
}

type Assignment @model @auth(rules: [{ allow: public }]) {
  id: ID!
  assignmentTitle: String!
  description: String!
  courseID: ID! @index(name: "byCourse")
}
```
This is my schema file. Initially I created this schema in a windows system and everything was working fine(model generation). Once I switched to Mac and pulled the amplify project from remote the **amplify codegen models** command removes the relationship ids from the generated model for a many to many relationship.

**THESE ARE THE MODELS GENERATED BY AMPLIFY COMMAND**
<img width="1035" alt="Screenshot 2021-12-28 at 5 13 17 PM" src="https://user-images.githubusercontent.com/96001398/147563044-de5da470-0fd1-4f7a-9df4-6b4be75236c3.png">

<img width="1440" alt="Screenshot 2021-12-28 at 5 32 01 PM" src="https://user-images.githubusercontent.com/96001398/147564375-e74b4ddd-3fc8-4c9c-aae9-f592b19f6ba9.png">

As you can see here the courseID,studentID are removed by the command which is required for me to query the join tables based on either one of these ids.

### Expected behavior

The expected behaviour was that the relationships ids should remain intact across all operating systems. It still works fine in my windows system. There was no change in the generated models.

### Reproduction steps

1. Create a new amplify project with next's
2. Create a new schema with one or more many to many relationship in a windows system and push it to remote.
3. Generate models and push it to git or any other version control system
3. Pull the project in a Mac system with amplify api id
4. Execute amplify codegen models

Now it will remove the relationships id in the join table

### GraphQL schema(s)

<details>

```graphql
type SystemAdmin @model @auth(rules: [{ allow: public }]) {
  id: ID!
  systemAdminName: String
  systemAdminEmail: String
  systemAdminID: Int
}

type School @model @auth(rules: [{ allow: public }]) {
  id: ID!
  schoolName: String!
  schoolAddress: String!
  schoolFrontEndID: Int
  Teachers: [Teacher!] @hasMany(indexName: "bySchool", fields: ["id"])
  Admins: [Admin!] @hasMany(indexName: "bySchool", fields: ["id"])
  Students: [Student!] @hasMany(indexName: "bySchool", fields: ["id"])
  Courses: [Course!] @hasMany(indexName: "bySchool", fields: ["id"])
}

type Admin @model @auth(rules: [{ allow: public }]) {
  id: ID!
  adminName: String!
  adminEmail: String!
  schoolID: ID! @index(name: "bySchool")
  adminID: Int
}

type Teacher @model @auth(rules: [{ allow: public }]) {
  id: ID!
  teacherName: String!
  teacherEmail: String!
  schoolID: ID! @index(name: "bySchool")
  teacherID: Int
  courses: [Course!] @manyToMany(relationName: "TeacherCourse")
}

type Course @model @auth(rules: [{ allow: public }]) {
  id: ID!
  courseName: String!
  schoolID: ID! @index(name: "bySchool")
  students: [Student!] @manyToMany(relationName: "StudentCourse")
  assignments: [Assignment!] @hasMany(indexName: "byCourse", fields: ["id"])
  teachers: [Teacher!] @manyToMany(relationName: "TeacherCourse")
}

type Student @model @auth(rules: [{ allow: public }]) {
  id: ID!
  studentName: String
  studentEmail: String
  sisID: Int
  schoolID: ID! @index(name: "bySchool")
  courses: [Course!] @manyToMany(relationName: "StudentCourse")
}

type Assignment @model @auth(rules: [{ allow: public }]) {
  id: ID!
  assignmentTitle: String!
  description: String!
  courseID: ID! @index(name: "byCourse")
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

And recently from my windows system I migrated schema from GraphQL Transformer version 1 to version 2.

**Comment by frimfram** [comment]
If you initially create this schema in Mac, do you get the class with teacherID and courseID?

**Comment by guruken** [comment]
```javascript
// All posts for a given editor
const postsByEditor = (await DataStore.query(PostEditor)).filter(
    pe => pe.editor.id === editor.id
).map(pe => pe.post);

// All editors on a given post
const editorsByPost = (await DataStore.query(PostEditor)).filter(
    pe => pe.post.id === post.id
).map(pe => pe.editor);

// All editors of posts where title contains "first"
const editorsOfFirstPosts = (await DataStore.query(PostEditor)).filter(
    pe => pe.post.title.includes("first")
).map(pe => pe.editor);

// All editors of posts where title is long
const editorsWithLongTitles = (await DataStore.query(PostEditor)).filter(
    pd => pe.post.title.length > 20
).map(pe => pe.editor);
```
This is the example query provided in the docs. It gets all the data in the join model and the filtering is done in UI. Now without the xyzID in the join model, is there any other way to query the data with constraints applied?

Something like this?
```javascript
const students = await DataStore.query(StudentCourse,c=>c.student.studentID("eq",id));
```

**Comment by frimfram** [comment]
Similar to what you have there, ``` c.student.id ``` can be used to refer to c.studentID that was removed.

```const students = (await DataStore.query(StudentCourse)).filter (c => c.student.id === student.id);```

**Comment by guruken** [comment]
Can we express it via query? I have concerns of excessive performance drag from filtering the data at the edge.

**Comment by alharris-at** [comment]
Hi @guruken - DataStore performs all filtering locally in general, unless you're performing a selective sync of the remote catalog https://docs.amplify.aws/lib/datastore/data-access/q/platform/js/#query-data. Performing a top-level `filter` statement as recommended by Jean above is effectively the same as expressing the same thing as a query filter, and there shouldn't be a significant performance hit.

If you're trying to reduce the amount of data filtered locally, there is a selective sync feature, but it appears to exist more for gross filters rather than business logic. Docs are available here if you're interested though https://docs.amplify.aws/lib/datastore/sync/q/platform/js/#selectively-syncing-a-subset-of-your-data

**Comment by guruken** [comment]
What if we had a log table with millions of records that'd be prohibitive to sync to client in its entirety. Yet we need to build a UI where a user can page through the logs and maybe search logs by some values. What's the recommendation for this type of data?

**Comment by alharris-at** [comment]
In that case you may want to leverage Amplify API category instead of DataStore for that access pattern https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/js/, since it would push the logic for joins and filters up into the AppSync layer, rather than relying on your client to perform that.

**Comment by guruken** [comment]
```ts
const students = (await DataStore.query(StudentCourse)).filter (c => c.student.id === student.id);
```
This is the solution suggested by @frimfram. This is good for filtering data in join tables(models). But what if I have to listen changes like this

```ts
DataStore.observeQuery(StudentCourse,(c)=>c.studentID("eq",id)).subscribe(({items})=>setCourses(items));
```
How to achieve this without Model API exposing studentID or CourseID?

**Comment by phani-srikar** [comment]
Hi Can you please update your CLI, make sure you're using the same version from windows, Mac and confirm that the issue still exists? Thanks

**Comment by phani-srikar** [comment]
Hi @guruken, as per your other question about ObserveQuery, can you please try `DataStore.observeQuery(StudentCourse,(c)=>c.student.id===id).subscribe(({items})=>setCourses(items));`. Thanks
