### ISSUE TITLE
Typescript transformer issue: @belongsto doesn't generate parent ID field

### ISSUE THREAD

**Issue by khusmann** [aws-amplify/amplify-codegen#349]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/master/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### Amplify CLI Version

7.6.5

### What operating system are you using?

Ubuntu

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

When using @belongsto, the parent ID key is not being generated. I think it might be related to this issue: https://github.com/aws-amplify/amplify-cli/issues/9236

### Expected behavior

Use of @belongsto should automatically generate a field to hold the ID of the parent.

### Reproduction steps

1. Set schema to:

```graphql
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @hasMany
}

type Post @model {
  id: ID!
  title: String!
  blog: Blog @belongsTo
}
```

2. Run `amplify codegen models`
3. View ./src/index.t.ts:

```typescript
export declare class Post {
  readonly id: string;
  readonly title: string;
  readonly blog?: Blog;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  constructor(init: ModelInit<Post, PostMetaData>);
  static copyOf(source: Post, mutator: (draft: MutableModel<Post, PostMetaData>) => MutableModel<Post, PostMetaData> | void): Post;
}
```
I'd expect to see a field something like `readonly blogPostsId?: string;` Without it, I can't add posts to blogs with the DataStore

### GraphQL schema(s)

<details>

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

It gets worse. When I add a field to @belongsto, it ignores the field... but then magically puts a autogenerated parent id key in there:

Schema:

```graphql
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @hasMany
}

type Post @model {
  id: ID!
  title: String!
  foo: ID!
  blog: Blog @belongsTo(fields: ["foo"])
}
```

Resulting ./src/model/index.d.ts:

```typescript
export declare class Post {
  readonly id: string;
  readonly title: string;
  readonly blog?: Blog;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  readonly blogPostsId?: string;
  constructor(init: ModelInit<Post, PostMetaData>);
  static copyOf(source: Post, mutator: (draft: MutableModel<Post, PostMetaData>) => MutableModel<Post, PostMetaData> | void): Post;
}
```

Note how the `foo` field disappeared and was replaced with `blogPostsId`

Then, when trying with indexes:

```graphql
type Blog @model {
  id: ID!
  name: String!
  posts: [Post] @hasMany(indexName: "byBlog", fields: ['id'])
}

type Post @model {
  id: ID!
  title: String!
  foo: ID! @index(name: "byBlog")
  blog: Blog @belongsTo(fields: ["foo"])
}
```
Resulting ./src/models/index.d.ts:

```typescript
export declare class Post {
  readonly id: string;
  readonly title: string;
  readonly blog?: Blog;
  readonly createdAt?: string;
  readonly updatedAt?: string;
  constructor(init: ModelInit<Post, PostMetaData>);
  static copyOf(source: Post, mutator: (draft: MutableModel<Post, PostMetaData>) => MutableModel<Post, PostMetaData> | void): Post;
}
```

Poof, `blogPostsId` is gone, but `foo` still isn't there either...

Thanks for looking in to this!

**Comment by svidgen** [comment]
FYI, there's was a discussion question on the JS repo with a few reactions about this too.

https://github.com/aws-amplify/amplify-js/discussions/9499

**Comment by hpwtaee** [comment]
I'm having the same issue. In my case I'm using DataStore but trying to selectively sync a subset of data against a userId field (at runtime) that again vanishes after generating models so I'm a little stuck. Is this bug currently being addressed?

**Comment by nixmove** [comment]
same probrem :(

**Comment by AaronZyLee** [comment]
The fix is currently included in the [custom PK PR](https://github.com/aws-amplify/amplify-codegen/pull/427). As the JS and native platforms behave differently in the usage of those indexes, we are now scoping the fix to JS only.

**Comment by AlexChaseJones** [comment]
Hi @AaronZyLee, I see that PR has been merged! I don't fully understand the relationship between amplify-codegen and @amplify/cli; but is there a way to use the latest amplfiy-codegen in a JS project?

**Comment by Jackson3195** [comment]
Any updates on this? Seems like I also have run into this issue on amplify-js v5.0.7

**Comment by zevi-wiply** [comment]
Having exact same issue as @hpwtaee, is there still no fix for this?

**Comment by david-mcafee** [comment]
Looks like https://github.com/aws-amplify/amplify-codegen/pull/427 has been merged. I just tested this with the following test code + the latest versions of Amplify and the CLI, and things are working as expected:

```typescript
import "./App.css";
import { DataStore } from "aws-amplify";
import { Pathway, PathwayPitstop } from "./models";

function App() {
  const test = async () => {
    const pathway = await DataStore.save(
      new Pathway({
        title: `Pathway title ${Date.now()}`,
        description: "Pathway Description",
        thumbnail: "thumbnail",
      })
    );

    console.log("pathway:", pathway);

    let pathwayPitstop;

    // If using TypeScript, check that the pathway is not `undefined`
    if (pathway) {
      pathwayPitstop = await DataStore.save(
        new PathwayPitstop({
          pathwayID: pathway.id,
          positionX: 100,
          positionY: 100,
        })
      );
    }

    console.log("pathwayPitstop:", pathwayPitstop);

    const queriedPathway = await DataStore.query(Pathway, pathway.id);

    // If using TypeScript, check that the queriedPathway is not `undefined`
    if (queriedPathway) {
      const pathwayPitstops = await queriedPathway.pathwayPitstops.toArray();
      console.log("pathwayPitstops", pathwayPitstops);
    }
  };

  return (
    <div className="App">
      <header className="App-header">
        <button onClick={test}>Create Records + Query</button>
      </header>
    </div>
  );
}

export default App;
```

Closing this ticket since this issue has been remediated. @khusmann  - if you are still running into issues, please don't hesitate to re-open the ticket. Thanks!
