### ISSUE TITLE
API '$ amplify codegen models': types without @model directive

### ISSUE THREAD

**Issue by lazy-var** [aws-amplify/amplify-codegen#36]
`API`, `Bug`, `code-gen`

### **Describe the bug**
`$ amplify codegen models` amplify API (preview) command is not generating front-end code for **types without `@model`** directive, while traditional API sdk generates them.

**Amplify CLI Version**: `amplify -v`: 4.6.0

**Platform target**: **iOS**

### **To Reproduce**

```
type Task @model {
    id: ID!
    title: String!
    description: String
    status: String
}
type Note {
    id: ID!
    content: String!
}
```

When generating front-end code with iOS target:

- **API.swift** (old sdk): contains strongly typed code for both `Task`s and `Note`s
- **/amplify/generated/models/** (new preview): only contains code to work with `Task`s

### **Expected behavior**
I expected to get front-end code to manage graphQL types without backend DB deployment (without `@model`). So I can hook up my custom resolvers using the new amplify iOS/android framework (preview).

**Comment by AaronZyLee** [comment]
@lazy-var The latest version of modelgen already has support for swift non-model generation. I close this issue for now but please feel free to reopen if your problem is not resolved.

**Comment by charlesfayal** [comment]
> 

Can you point us to directions for this?
