### ISSUE TITLE
Naming a type "Subscription" creates invalid subscription related code

### ISSUE THREAD

**Issue by hisham** [aws-amplify/amplify-codegen#365]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.17.6

### Amplify CLI Version

7.6.5

### What operating system are you using?

Mac

### Amplify Codegen Command

codegen

### Describe the bug

Having a type as follows creates invalid subscription-related code: 

```
type Subscription {
  myId: ID!
}

```

Creates the following in subscriptions.graphql: 

```
# this is an auto generated file. This will be overwritten
subscription MyId {
  myId
}
```

And creates this in API.service.ts: 

```
  MyIdListener: Observable<
    SubscriptionResponse<MyIdSubscription>
  > = API.graphql(
    graphqlOperation(
      `subscription MyId {
        myId
      }`
    )
  ) as Observable<SubscriptionResponse<MyIdSubscription>>;
}
```

### Expected behavior

No subscription code should be created. Allow me to create a type called "Subscription" or tell me that is a reserved keyword. 

### Reproduction steps

See above

### GraphQL schema(s)

See above

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by AaronZyLee** [comment]
`Subscription` is a reserved keyword, which is auto-generated by the gql transformer. The behavior is very similar to `Query`, `Mutation`. If you have these reserved type defined, it will be considered as your customized fields which are added to the generated fields as well. The code is expected because you add your own `Subscription` (the same as `Query`, `Mutation`.
