### ISSUE TITLE
Running `amplify codegen models` doesn't generate correct typescript types for GraphQL nullable fields

### ISSUE THREAD

**Issue by mogarick** [aws-amplify/amplify-codegen#383]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/master/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm i -g @aws-amplify/cli --legacy-peer-deps

### If applicable, what version of Node.js are you using?

14.7.3

### Amplify CLI Version

7.6.14

### What operating system are you using?

MacOS 11.6.3 (20G415)

### Amplify Codegen Command

codegen models

### Describe the bug

TS type definitions file is being created with fields declared in the `.graphql` file as optional (ex. `fieldName?: string` instead of nullable (ex. `fieldName?: string|null`)

### Expected behavior

The TS type definitions file being created should include all fields declared as nullable with the corresponding `|null` union type.

### Reproduction steps

Given a graphql type sucha as:

``` graphql

type Person @model {
  id: ID! @primaryKey
  name: String!
  lastName: String!
  birthdate: String
}

```

the field  `birthdate` is declared as nullable, so the expected ts declaration in the `.d.ts` file should be something like:

``` typescript
export declare class Person {
  readonly id: string;
  readonly name: string;
  readonly lastName: string;
  readonly birthdate?: string | null;
  constructor(init: ModelInit<Person>);
  static copyOf(source: Person, mutator: (draft: MutableModel<Person>) => MutableModel<Person> | void): Person;
}
```

but the current generated code is creating the field declaration only as `birthdate?: string` without the `|null` part:

``` typescript
export declare class Person {
  readonly id: string;
  readonly name: string;
  readonly lastName: string;
  readonly birthdate?: string;
  constructor(init: ModelInit<Person>);
  static copyOf(source: Person, mutator: (draft: MutableModel<Person>) => MutableModel<Person> | void): Person;
}
```

### GraphQL schema(s)

<details>

```graphql
type Person @model {
  id: ID! @primaryKey
  name: String!
  lastName: String!
  birthdate: String
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by mikepschneider** [comment]
Fix should be present in the next release

**Comment by mogarick** [comment]
@mikepschneider @dpilch  thanks!

When is the next release gonna be published? :)

**Comment by danrivett** [comment]
While I understand the valid argument for updating these types, I will say this recent change has caused our application a lot of compilation errors since we use simplified types where we equate an optional GraphQL type to an optional Typescript type for simplicity and use `X == null` evaluations to determine if a value is set or not (rather than `X === null || X === undefined`).

But I do understand the motivation for this change, I just wish it was made configurable so existing applications could opt out of these type changes as it's going to cause a lot of ripple effects in our codebase for little benefit.

**Comment by danrivett** [comment]
Given the PR was marked as a feature and it introduced compability issues with existing apps such as ours, I am suggesting is retrospectively add a new cli feature flag to avoid breaking existing applications like ours by adding the following to [featureFlags.ts](https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli-core/src/feature-flags/featureFlags.ts#L705) in the [aws-amplify/amplify-cli](https://github.com/aws-amplify/amplify-cli/) repo:

```ts
      {
        name: "generateTypescriptNullsForOptionals",
        type: "boolean",
        defaultValueForExistingProjects: false,
        defaultValueForNewProjects: true,
      },
```

And then add a guard in front of the change to [appsync-typescript-vistor](https://github.com/aws-amplify/amplify-codegen/blob/master/packages/appsync-modelgen-plugin/src/visitors/appsync-typescript-visitor.ts#L250) added in #385 

At the top of [appsync-typescript-visitor.ts](https://github.com/aws-amplify/amplify-codegen/blob/master/packages/appsync-modelgen-plugin/src/visitors/appsync-typescript-visitor.ts#L18):

```ts
const generateNullsForOptionals = FeatureFlags.getBoolean('codegen.generateTypescriptNullsForOptionals');
```

Then updating the recent change to the getNativeType() method by #385 

```patch
- const nullableTypeUnion = isNullable ? ' | null' : '';
+ const nullableTypeUnion = isNullable && generateNullsForOptionals ? ' | null' : '';
```

Thoughts?

**Comment by SebSchwartz** [comment]
Running the same problem.
When we are deploying our schema (`amplify push`), we have typings with null generated. And when we are executing `amplify codegen models`, we don't have null values.
I'm ok with null value as we changed our codebase for this but both process should generate the same typings...

**Comment by danrivett** [comment]
Also FYI, we're still pinned on 7.6.24 to avoid us having to make code changes across multiple repos (as mentioned above) so we haven't tested recent versions, but assume it hasn't changed since #385 was merged.

At some point we'll need to reevaluate this as we can't stay on an old version indefinitely, we just currently have other higher priority AppSync work to focus on first.

**Comment by SebSchwartz** [comment]
@danrivett Ok but how can we get the same typings result when publishing new API version `amplify push` and doing `amplify codegen models`?
