### ISSUE TITLE
Codegen for iOS AppSync creates incorrect GraphQL document for maximum depth 2

### ISSUE THREAD

**Issue by lawmicha** [aws-amplify/amplify-codegen#40]
**Describe the bug**

The schema is a User model with [Post] model. 
```
type User @model {
  id: ID!
  fullName: String!
  emailAddress: String!
  posts: [Post] @connection(name: "UserPostConnection")
}

type Post @model {
  id: ID!
  text: String!
  user: User @connection(name: "UserPostConnection")
  createdAt: String
  updatedAt: String
}
```

in Amplify CLI 4.12.0 (current version installed on my system). `amplify add api`, `amplify push` and choosing max depth of 2 is generating correct selection set in the API.swift file used for AppSyncClient. See https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/376#issuecomment-613717842 for more context

in 4.17.2, as observed by another developer, when setting the max depth to 2, the "posts" in the "user" selection set is not being generated correctly. See https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/376#issuecomment-614197235 for more context. Setting it to 3 works as expected. where it be returned as part of a call to get user, ie. selection set contains `posts { items { <fields> } }`

**Amplify CLI Version**
Some issue introduced between > 4.12.0 and 4.17.2

**Expected behavior**
A maximum depth of 2 should mean that the selection set that is generated contains the "posts" inside the "user".
```
query GetUser($id: ID!) {
    getUser(id: $id) {
    __typename
    id
    fullName
    emailAddress
    posts {
      __typename
      items {
        __typename
        id
        text
        createdAt
        updatedAt
      }
      nextToken
    }
  }
}
```
but instead it is generating 
```
query GetUser($id: ID!) {
   getUser(id: $id) {
    __typename
    id
    fullName
    emailAddress
    posts {
      __typename
      nextToken
    }
  }
}
```

**Additional context**
Didn't notice any transformer changes in the changelog 
https://github.com/aws-amplify/amplify-cli/blob/master/packages/amplify-cli/CHANGELOG.md
maybe it's somewhere in transformer/codegen https://github.com/aws-amplify/amplify-cli/blob/master/packages/graphql-transformer-common/CHANGELOG.md

**Comment by phani-srikar** [comment]
This is going to be a breaking change for existing customers as they would receive additional data than what they already subscribed for using `maxDepth`. As I explained in #23 this situation can be handled by the developer by increasing the value of `maxDepth`. Refer [the doc](https://docs.amplify.aws/cli/graphql-transformer/codegen#statement-depth).  Closing this issue until we get more requests for this from the developers.
