### ISSUE TITLE
Non model type with id field in java code generation

### ISSUE THREAD

**Issue by aladine** [aws-amplify/amplify-codegen#409]
The issue still exists. When running with the latest awsamplify-cli (npm i -g @aws-amplify/cli at 8.0.0), there is no  IdStep interface in the generated file.

Is there anyway I could make sure I have the latest amplify-codegen.

_Originally posted by @aladine in https://github.com/aws-amplify/amplify-codegen/issues/231#issuecomment-1095351856_

**Comment by AaronZyLee** [comment]
Referred comment here: https://github.com/aws-amplify/amplify-codegen/issues/231#issuecomment-1096986791
