### ISSUE TITLE
Customizable $input per GraphQL operation on new API/Datastore plugins

### ISSUE THREAD

**Issue by lazy-var** [aws-amplify/amplify-codegen#41]
`iOS`, `Android`, `JS`, `API` plugin, `DataStore` plugin, `code-gen`, `feature-request`

**Is your feature request related to a problem? Please describe.**
With previous API (iOS-sdk) you could go custom with GraphQL mutation/query input attributes schema definition, and front end code would get generated accordingly.

i.e. `Your GraphQL input attributes could be a subgroup of model's available attributes. `

Now with new plugins it is not possible anymore as frontend modules (at least iOS) have 'hardcoded' ([on delete](https://github.com/aws-amplify/amplify-ios/blob/389cb6e5d708553287265314d294af0b15af6c96/AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLDocument%2BDeleteSyncMutation.swift#L60-L69)) or all fields included ([on update or create](https://github.com/aws-amplify/amplify-ios/blob/389cb6e5d708553287265314d294af0b15af6c96/AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument/GraphQLDocument%2BMutation.swift#L61-L73)). So GraphQL query input schema would always need to include all model attributes, plus doesn't allows to go custom because of 'hardcoded' on deletion.

**Describe the solution you'd like**
My proposal is to do an optional inclusion on model schema definition at front-end code level, where you (and codegen) can define which concrete fields would be included as `$input` on each GraphQL query type.

i.e. (iOS):
https://github.com/aws-amplify/amplify-ios/blob/f4b0423ee3a4af09af85c8e32d78a180003db6af/Amplify/Categories/DataStore/Model/ModelSchema.swift#L62-L67
```
public struct ModelSchema {


    public let name: String
    public let pluralName: String?
    public let fields: ModelFields
    public let attributes: [ModelAttribute]
```

Add:
```
    public let operationInputFields: [String:ModelFields]
```
Where String is GraphQL operation's name, and ModelFields includes the definition for that operation input.

So every time an operation is executed only those fields are added, by implementing a check+cribe here on the corresponding operation type file: https://github.com/aws-amplify/amplify-ios/tree/389cb6e5d708553287265314d294af0b15af6c96/AmplifyPlugins/Core/AWSPluginsCore/Model/GraphQLDocument

**Comment by phani-srikar** [comment]
This request could be handled along with #42 and might require some refactor to eliminate DataStore's dependency on `ID` field and allow developers to specify custom `ID` fields.
