### ISSUE TITLE
add codegen for Flutter

### ISSUE THREAD

**Issue by uny** [aws-amplify/amplify-codegen#418]
### Is this feature request related to a new or existing Amplify category?

api

### Describe the feature you'd like to request

Currently, the options for `amplify add codegen` are:
```bash
? Choose the type of app that you're building 
❯ android 
  ios 
  javascript 
```
Could you support Flutter?

### Describe the solution you'd like

```bash
$ amplify add codegen
? Choose the type of app that you're building 
❯ android 
  ios 
  javascript 
  flutter
```

### Describe alternatives you've considered

I would like to codegen without `amplify init`.
https://github.com/aws-amplify/amplify-cli/issues/247

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by alharris-at** [comment]
Amplify codegen does support flutter at this point in time.

For information on how to execute this, please refer to the docs https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/flutter/#generate-todo-model-class

**Comment by patrick-hieber** [comment]
Is it possible to do this without the Amplify backend?
For Android, iOS and Javascript we can generate the code by setting it up using `amplify add codegen` and following the instructions.
However I haven't found a solution for Flutter to generate code without setting up the complete Amplify backend.

**Comment by patrick-hieber** [comment]
> Amplify codegen does support flutter at this point in time.
> 
> For information on how to execute this, please refer to the docs https://docs.amplify.aws/lib/graphqlapi/getting-started/q/platform/flutter/#generate-todo-model-class

@alharris-at is it possible to do this without the Amplify backend?
For Android, iOS and Javascript we can generate the code by setting it up using `amplify add codegen` and following the instructions.
However I haven't found a solution for Flutter to generate code without setting up the complete Amplify backend.
