### ISSUE TITLE
Supporting TypeScript

### ISSUE THREAD

**Issue by januswel** [aws-amplify/amplify-codegen#443]
**Is your feature request related to a problem? Please describe.**
TypeScript does not appear as an option in the language selection when running `amplify pull`.
Therefore, the only option is to output in JavaScript, but this may cause coding errors when using it.

**Describe the solution you'd like**
Supporting TypeScript at UI code generation

**Describe alternatives you've considered**
nothing

**Additional context**
none

**Comment by alharris-at** [comment]
Codegen does support typescript. It can be selected by adding codegen to the project, or by updating via `amplify update codegen`. If you're describing the generated ui (react) components, then a decision was made to default to JS + typings files, which provides a similar DX to TS while operating in-editor and with tsc/etc.

<img width="450" alt="Screenshot 2023-03-21 at 12 17 15 PM" src="https://user-images.githubusercontent.com/91494052/226717474-87dc721b-5838-471b-8217-04736ab76200.png">

Closing this issue.

**Comment by januswel** [comment]
Thank you very much for supporting TypeScript.
Awesome!!!
