### ISSUE TITLE
Command 'amplify add codegen' don't follow configuration

### ISSUE THREAD

**Issue by pippo111** [aws-amplify/amplify-codegen#46]
**Describe the bug**
When setting up `codegen` described here: https://docs.amplify.aws/cli/graphql-transformer/codegen#workflows generated code is placed under different directory than pointed. When choosing default directories everything is generated ok.

**Amplify CLI Version**
4.41.2

**To Reproduce**
1. Create and configure AppSync graphql schema
2. Export `schema.json` to your project directory
3. Run `amplify add codegen`
4. Enter this configuration:
```
amplify add codegen
? Choose the type of app that you're building javascript
? What javascript framework are you using react
? Choose the code generation language target typescript
? Enter the file name pattern of graphql queries, mutations and subscriptions aws/graphql/**/*.ts
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 2
? Enter the file name for the generated code aws/API.ts
? Do you want to generate code for your newly created GraphQL API Yes
✔ Generated GraphQL operations successfully and saved at src/graphql
✔ Code generated successfully and saved in file aws/API.ts
```

**Expected behavior**
- Generated GraphQL operations should be saved into `aws/graphql`
- API.ts code should be generated

**Actual behavior**
- Generated GraphQL operations should be saved into `src/graphql`
- API.ts is created under right directory but it is empty

**Desktop (please complete the following information):**

- OS: Linux Manjaro
- Node Version. v12.20.1

**Log output**
```
2021-01-24T09:47:40.071Z|info : amplify version core  {"version":true,"yes":false}
2021-01-24T09:48:10.804Z|info : amplify add codegen
```

**Comment by AaronZyLee** [comment]
Close this issue due to the solution PR https://github.com/aws-amplify/amplify-cli/pull/6530

**Comment by pippo111** [comment]
@AaronZyLee It is still reproducable on v4.44.0

`API.ts` is landing on correct custom directory
`queries.ts` is still landing in default directory, but it should be placed here:

`? Enter the file name pattern of graphql queries, mutations and subscriptions aws/graphql/**/*.ts`

**Comment by AaronZyLee** [comment]
@pippo111 The fix PR was merged at the amplify-cli repo but not released yet. I talk to the cli team and they say they will do a release for this week. I will notify you ASAP once they release the changes.

**Comment by AaronZyLee** [comment]
@pippo111 The amplify cli v4.44.1 is released with the latest codegen changes.

**Comment by pippo111** [comment]
It works as expected. Thanks!
