### ISSUE TITLE
ModelIndexes not defined using Amplify code gen

### ISSUE THREAD

**Issue by marendra** [aws-amplify/amplify-codegen#488]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

sudo npm install -g @aws-amplify/cli

### If applicable, what version of Node.js are you using?

v17.4.0

### Amplify CLI Version

10.0.0

### What operating system are you using?

Mac OS Monterey

### Amplify Codegen Command

codegen models

### Describe the bug

the new codegen models, add modelIndex that was not defined in flutter, i revert back to old amplify 9.2.1, and the error was gone, please fix the new one

### Expected behavior

I expected the modelIndex is defined in the flutter

### Reproduction steps

amplify codegen models

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by AaronZyLee** [comment]
@marendra Hi I am not able to reproduce the issue. Could you share your GraphQL schema(`amplify/backend/api/${api_name}/schema.graphql`) and the feature flag config (`amplify/cli.json`)?

**Comment by marendra** [comment]
okay here it is the schema :

   

type User @model
@auth(
  rules:[
    {allow:owner,operations:[read,create,delete,update]}
    {allow:private, operations:[read]}
  ]
)

{
id: ID!  
user: ID! @index(name:"byUserId",queryField:"queryByUserId")
name: String!
email: String! @index(name:"byEmail",queryField:"queryByEmail")
userName: String! @index(name:"byUserName",queryField:"queryByUserName")
goodDeedsTotal: Int!
followersTotal: Int!
followingTotal: Int!
profileImage: String
backgroundImage: String
userBio: String
created: Float!
birthDate: Float!
latitude: Float!
longitude: Float!
city: String!
}


type Relationship 
@model
@auth(
  rules:[
    {allow:owner, operations:[read,create,delete,update]}
    {allow:private,operations:[read]}
  ]
)
{
  id: ID!
  followee: String! @primaryKey(sortKeyFields:["followers"])
  followeeName: String!
  followeeImageUrl: String!
  followersName: String!
  followersImageUrl: String!
  followers: String! @index(name:"searchFollowing", queryField:"queryByFollowing")

}



type Post
@model
@auth(
  rules:[
    {allow:owner,operations:[read,create,delete,update]}
    {allow:private,operations:[read]}
  ]
)
{
  id:ID!
  user:ID! @primaryKey(sortKeyFields:["created"])
  created: Float!
  title: String!
  description: String!
  imageUrl: String!
}

type Timeline
@model
@auth(
    rules:[
        {allow:private,provider:userPools operations:[read]}
        {allow:private,provider:iam,operations:[read,create,delete,update]}
    ]
)
{
  
  user:ID! @primaryKey(sortKeyFields:["created"])
  created: Float!
  title: String!
  description: String!
  imageUrl: String!
  postId:ID! @index(name:"timelineBy",queryField:"queryByPost")
  comment:Int!
  like:Int!
}


and the cli.json

{
  "features": {
    "graphqltransformer": {
      "addmissingownerfields": true,
      "improvepluralization": false,
      "validatetypenamereservedwords": true,
      "useexperimentalpipelinedtransformer": true,
      "enableiterativegsiupdates": true,
      "secondarykeyasgsi": true,
      "skipoverridemutationinputtypes": true,
      "transformerversion": 2,
      "suppressschemamigrationprompt": true,
      "securityenhancementnotification": false,
      "showfieldauthnotification": false,
      "usesubusernamefordefaultidentityclaim": true,
      "usefieldnameforprimarykeyconnectionfield": false,
      "enableautoindexquerynames": false,
      "respectprimarykeyattributesonconnectionfield": false,
      "shoulddeepmergedirectiveconfigdefaults": false,
      "populateownerfieldforstaticgroupauth": false
    },
    "frontend-ios": {
      "enablexcodeintegration": true
    },
    "auth": {
      "enablecaseinsensitivity": true,
      "useinclusiveterminology": true,
      "breakcirculardependency": true,
      "forcealiasattributes": false,
      "useenabledmfas": true
    },
    "codegen": {
      "useappsyncmodelgenplugin": true,
      "usedocsgeneratorplugin": true,
      "usetypesgeneratorplugin": true,
      "cleangeneratedmodelsdirectory": true,
      "retaincasestyle": true,
      "addtimestampfields": true,
      "handlelistnullabilitytransparently": true,
      "emitauthprovider": true,
      "generateindexrules": true,
      "enabledartnullsafety": true
    },
    "appsync": {
      "generategraphqlpermissions": true
    },
    "latestregionsupport": {
      "pinpoint": 1,
      "translate": 1,
      "transcribe": 1,
      "rekognition": 1,
      "textract": 1,
      "comprehend": 1
    },
    "project": {
      "overrides": true
    }
  },
  "debug": {
    "shareProjectConfig": true
  }
}

**Comment by marendra** [comment]
also here is the error message in the flutter models/user.dart

<img width="1136" alt="Screen Shot 2022-09-09 at 00 12 18" src="https://user-images.githubusercontent.com/1898987/189184271-139940c5-77de-4114-84dd-4ae111904444.png">

**Comment by AaronZyLee** [comment]
@marendra Just consult with the amplify flutter team. The minimum version supporting the index is `amplify-flutter@0.6.7`. Could you update the amplify flutter library and check if the error still exists?

**Comment by marendra** [comment]
okay it works after change all to 0.6.7, currently im using the version 1.0.0-next.0+1, after change it all to 0.6.7 then it worked

**Comment by marendra** [comment]
thanks,closing the issue
