### ISSUE TITLE
`amplify migrate api` does not generate connected embedded type in the codegenerated files

### ISSUE THREAD

**Issue by manaswi223** [aws-amplify/amplify-codegen#496]
Codegen is able to successfully create codegenerated files for models (with `@model` directive) with @connection in Xcode. But for embedded types (without `@model` directive) that are migrated using `amplify migrate api`  that doesn't have `@connection` explicitly mentioned but having use case like:
```
type Category {
// other object assignments
}
```

```
type Position {
  // other object assignments
  category: Category!
}
```
then CLI throws error like:
```
warning: Model Position has field category of type Category but its not connected. Add the appropriate @hasMany/@belongsTo directive if you want to connect them.
```
Is this the expected behavior for embedded types?

**Comment by lawmicha** [comment]
i'm not entirely following this, is the problem that the embedded type of a model is being treated like a model type? like this?
```
type Todo @model {
  id: ID!
 content: String
  metadata: Metadata
}
type Metadata {
  tag: String
}
```

**Comment by manaswi223** [comment]
Thank you @lawmicha for looking into this! Yes, you are right the embedded type of a model is being considered like a model type. I can give you a sample schema in v1 transformer version so that you can reproduce it & run `amplify migrate api` to migrate it to v2 transformer version and see the behavior:
```
type CakeOrder @model @auth (rules: [{allow: owner, ownerField: "bill_id", identityClaim: "bill_id"}, 
{allow: private, provider: iam}])
@key(name: "cakeByCakeRecipeId", fields: ["cake_recipe_id"], queryField: "cakeByCakeRecipeId") {
id: ID!
cake_recipe_id: String!
bill_id: String!
date: AWSDate! 
location: Location
metaData: MetaData
}

type Location {
location_id: String!
name: String!
location_code: String!
chefDetails: ChefDetails
}

type ChefDetails {
chef_id: String!
chef_name: String!
chef_rating: Int!
}
```
here embedded types `Location` & `ChefDetails` are treated like a model without `@connection` directive explicitly mentioned. 
Steps to reproduce:
1. create an iOS app with amplify initialized
2. run `amplify add api`
```
? Select from one of the below mentioned services: GraphQL
Conflict detection (required for DataStore)
- Conflict resolution strategy: Auto Merge
? Select a setting to edit Authorization modes
? Choose the default authorization type for the API: Amazon Cognito User Pool
? Configure additional auth types? Yes
? Choose the additional authorization types you want to configure for the AP
I: IAM
```
3. now run `amplify migrate api` to transform from V1 --> V2
4. Now observe the warnings & see the migration tool command has not transformed my connections appropriately.
```
warning: Model CakeOrder has field location of type Location but its not connected. Add the appropriate @hasOne/@belongsTo directive if you want to connect them.
warning: Model Location has field chefDetails of type ChefDetails but its not connected. Add the appropriate @hasOne/@belongsTo directive if you want to connect them.

```

**Comment by manaswi223** [comment]
I was using 9.1.0 & `amplify migrate api` was unsuccessful, but I upgraded using `npm install -g @aws-amplify/cli` to 10.3.0 & my migration is successful :) Thank you 🙏
