### ISSUE TITLE
API > Schema > Remove list query > Get query not generated

### ISSUE THREAD

**Issue by conorw** [aws-amplify/amplify-codegen#502]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14

### Amplify CLI Version

10.3.2

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

na

### Amplify Categories

api

### Amplify Commands

codegen

### Describe the bug

If you want the model to not allow "list" queries, but allow "get" queries, BOTH the get and list queries are not generated
i.e. the following @model decoration will not generate a getTestObj query.
type tmpObj
@model(subscriptions: null, queries: { list: null }){
  id: ID!
  }

### Expected behavior

listTestObj is not generated, gettestObj is created

### Reproduction steps

1. Add api to project
2. Add following schema type tmpObj
@model(subscriptions: null, queries: { list: null }){
  id: ID!
  }
3. Deploy
4. amplify codegen

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type tmpObj
@model(subscriptions: null, queries: { list: null }){
  id: ID!
  }

```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by alharris-at** [comment]
Hi @conorw, thank you for reporting this issue. I believe you can mitigate this problem by enabling the `shoulddeepmergedirectiveconfigdefaults` in your `cli.json` file within the `amplify` directory. This is a feature flag which was released beginning in October of 2022.

In order for this update to take effect, you'll need to:
1. Ensure you've updated your amplify CLI (current latest version is 11.0.2)
2. Update the `cli.json` file to enable the `shoulddeepmergedirectiveconfigdefaults` flag.
3. Make a no-op change to your `schema.graphql` file to trigger a rebuild.
4. Push the backend with `amplify push`
5. Re-run codegen with `amplify codegen`

Feel free to re-open this issue if you encounter any issues with that flow.
