### ISSUE TITLE
No such module 'AWSAppSync'

### ISSUE THREAD

**Issue by ryancrunchi** [aws-amplify/amplify-codegen#505]
### Describe the bug

Building a newly iOS project with amplify library raises error:
`No such module 'AWSAppSync'` in `API.swift` generated file
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/4698648/193471540-829cb3f7-72cd-4a07-9177-4f773b7d2af5.png">

### Steps To Reproduce

1. I have followed the amplify iOS getting started tutorial : https://docs.amplify.aws/lib/project-setup/prereq/q/platform/ios/
2. Added packages with SPM : AWSAPIPlugin, AWSCognitoAuthPlugin, AWSDataStorePlugin
3. Using amplify with existing resources, I've used `amplifyconfiguration.json` and run `amplify codegen` in project folder : `API.swift` file and `graphql` folder were created with `subscriptions.graphql` `queries.graphql` `mutations.graphql` and `schema.json`. All my existing models and graphql stuff were generated well.
4. Added following code to `application(_, didFinishLaunching...)`:

```swift
do {
    try Amplify.add(plugin: AWSCognitoAuthPlugin())
    try Amplify.add(plugin: AWSAPIPlugin(modelRegistration: AmplifyModels()))
    try Amplify.configure()
} catch {
    print("An error occurred setting up Amplify: \(error)")
}
```
5. Build project

### Expected behavior

Project builds

### Amplify Framework Version

1.28.1

### Amplify Categories

API, Auth, DataStore

### Dependency manager

Swift PM

### Swift version

5.7

### CLI version

10.0.0

### Xcode version

14.0.1

### Relevant log output

```shell

```

### Is this a regression?

No

### Device

macOS 12.6 building for iPhone 14 Pro simulator

### iOS Version

iOS 14

**Comment by lawmicha** [comment]
This appears to be an unexpected behavior https://github.com/aws-amplify/amplify-codegen/issues/505#issuecomment-1297309388

If running `amplify pull` then `amplify codegen models` does not work, @ryancrunchi cannot generate the swift model types to be used with Amplify Libraries.

**Comment by ryancrunchi** [comment]
Hello, the steps are basically the following:

1. Create empty iOS project from Xcode with SPM
2. GraphQL api is created via CDK on an other repo
3. `amplify init`
```
Do you want to use an existing environment? Yes
? Choose the environment you would like to use: dev
Using default provider  awscloudformation
✔ Initialized provider successfully.
✅ Initialized your environment successfully.

Your project has been successfully initialized and connected to the cloud!
```

4. `amplify add codegen --apiId <apiId_at_step_2>`
```
✔ Getting API details
Successfully added API AppGraphQLApi to your Amplify project
? Enter the file name pattern of graphql queries, mutations and subscriptions graphql/**/*.graphql
? Do you want to generate/update all possible GraphQL operations - queries, mutations and subscriptions Yes
? Enter maximum statement depth [increase from default if your schema is deeply nested] 3
? Enter the file name for the generated code API.swift
? Do you want to generate code for your newly created GraphQL API Yes
✔ Downloaded the schema
✔ Generated GraphQL operations successfully and saved at graphql
✔ Code generated successfully and saved in file API.swift
```
5. Back to Xcode, add the generated graphql folder and API.swift file to project
6. Add AWSAppSync package
<img width="673" alt="image" src="https://user-images.githubusercontent.com/4698648/199350445-3a60ef8e-21a4-4d85-b966-0f866ad1a3c7.png">
7. Build and you should get `No such module 'AWSAppSync'` in API.swift file

**Comment by cohen72** [comment]
@ryancrunchi I was only able to get this working using cocoapods instead of SPM: `pod 'AWSAppSync', '~> 3.6.1'`

**Comment by dpilch** [comment]
Resolved by https://github.com/aws-amplify/amplify-codegen/pull/630
