### ISSUE TITLE
[Swift] Missing public initializer in generated class loader `AmplifyModels`

### ISSUE THREAD

**Issue by ynnadrules** [aws-amplify/amplify-codegen#506]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

16.16.0

### Amplify CLI Version

10.4.0

### What operating system are you using?

Mac

### Amplify Codegen Command

codegen models

### Describe the bug

The generated class `AmplifyModels` is public, however, there is no public initializer defined, so it can't be instantiated outside of its own swift module. 

### Expected behavior

For the generated class `AmplifyModels` to have a public initializer. 

### Reproduction steps

1. amplify codegen models
2. Inspect `AmplifyModels.swift` in your `amplify/generated/models` folder. 
3. See that it's missing a public initializer. 

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ynnadrules** [comment]
👀

**Comment by alharris-at** [comment]
Hi @ynnadrules - could you describe why you need to initialize this class? As far as I'm aware the only users of this will be the underlying models themselves, though I'm not particularly familiar w/ the swift implementation.

**Comment by ynnadrules** [comment]
Hi @alharris-at, thanks for checking in on this.

To answer your question: because the [docs](https://docs.amplify.aws/lib/datastore/getting-started/q/platform/ios/#code-generation-amplify-cli) show you having to do it to configure DataStore, like below:

```swift
@main
struct MyAmplifyApp: App {

    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }

    init() {
        do {
            // AmplifyModels is generated in the previous step
            let dataStorePlugin = AWSDataStorePlugin(modelRegistration: AmplifyModels()) // <== NOTE, THE INITIALIZATION HERE
            try Amplify.add(plugin: dataStorePlugin)
            try Amplify.configure()
            print("Amplify configured with DataStore plugin")
        } catch {
            print("Failed to initialize Amplify with \(error)")
        }
    }
}
```

In my use case, I've got a heavily modularized project where different components are in their own swift packages. The main App in turn imports those packages. 

I've configured the Amplify CLI tool to place the generated models into a Swift Package that my App depends on. Other packages depend on the package with the generated modules. Unfortunately, the `AmplifyModels` class doesn't get a public initializer generated, so I can't instantiate it at the App level since its initializer's access level is implicitly `internal` and only accessible within its package's Swift Module. 

Does this help clarify the issue?

Thanks!
