### ISSUE TITLE
Unable to update model after upgrade to CLI 10.4.0

### ISSUE THREAD

**Issue by duranmla** [aws-amplify/amplify-codegen#509]
**Which Category is your question related to?**
API

**Amplify CLI Version**
10.4.0

**Context**
I needed to add an attribute of `image` in my Post model and when I push it succeeded but when sending the request with all the data the new added attribute of `image` is not being added (I known it is being sent cause I activate the DEBUG logger and I see the request with all the data I intended to add). Of course, I don't think this is an issue as it is a crucial part of the Amplify functionality, nonetheless, I feel I am missing something.

Now that we are adding this `Lazy` and `Eager` models for each model there is something that I should do to being able to update models? 

Worth to mention that I have downgraded and then everything works as I expect to.

> I have already downgraded but maybe I need to clear the storage so DataStore pickups something that previously wasn't needed? How this new models work? https://github.com/aws-amplify/amplify-js/discussions/10600

**Comment by hisstoryxx** [comment]
> I am missing documentation about this change and `LazyLoadingDisabled` seems to be for Amplify internal usage. I need to do few things before tackling this again but I will keep you posted and thanks you a lot for taking the time to answer.

I am facing same ISSUE after amplify cli updates. Especially, it occurs when Using CREATE with Datastore in many to many relationship...like below
user and schedule has many to many relationships.
```
await DataStore.save(
            new ScheduleUser({
              user: dbUser,
              schedule: newSchedule,
            }),
          );
```
The code was working before updates!!!

I am agree with [duranmla](https://github.com/duranmla)'s opinion that need some documentation about this change...

**Comment by alharris-at** [comment]
Ahh yeah, it's the update to `aws-amplify: ^5.0.0` that's causing you to have issues. The v5 Major version of the Amplify JS library changes can be found here https://github.com/aws-amplify/amplify-js#amplify-5xx-has-breaking-changes-please-see-the-breaking-changes-below.

Feel free to reopen this issue if I'm slightly missing your concern, or it appears to be happening independent of an update to the `aws-amplify` library.
