### ISSUE TITLE
Can't change the location of models generated from 'src' to 'app'

### ISSUE THREAD

**Issue by judygab** [aws-amplify/amplify-codegen#565]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### Amplify CLI Version

4.16.0

### What operating system are you using?

Mac

### Amplify Codegen Command

codegen models

### Describe the bug

I updated `SourceDir` setting in `amplify/.config/project-config.json` from `src` to `app` and that now generates types inside the app folder for graphql, but when it comes to models it still creates a new folder named src and will store the files there. Any way I can update this?

### Expected behavior

Filed stored in app

### Reproduction steps

1. Configure Amplify
2. Run amplify-modelgen

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by alharris-at** [comment]
Hi @judygab - beginning in Amplify version 10 we added support for a `--output-dir` param in the CLI inputs, so executing `amplify codegen models --output-dir ./app` should achieve the goal you're looking for here. Feel free to reopen this issue if you have additional questions.
