### ISSUE TITLE
EPERM: operation not permitted, lstat amplify-codegen-temp\temp-console-log.txt

### ISSUE THREAD

**Issue by pavankumarn05** [aws-amplify/amplify-codegen#574]
Hi Team,
I am trying to do a amplify push and getting the below error:
**EPERM: operation not permitted, lstat 'C:\Users\PK\Desktop\WORKSPACE\my-project\amplify-codegen-temp\temp-console-log.txt'**

Since I am using windows, amplify is not recognized. Hence the actual command I am trying is below. 

**C:\Users\PK\AppData\Roaming\npm\amplify.cmd push --allow-destructive-graphql-schema-updates**

But I get the above mentioned error. Seems like permission issue but I am not sure how/what/where to change the permissions. 
Please suggest.

**Comment by alharris-at** [comment]
Hi @pavankumarn05, what version of the Amplify CLI were you using? I believe there was a bug in the version released as 11.0.4 and 11.0.5 which had to do with access to some local files, which has been resolved in the latest version.
