### ISSUE TITLE
Downloading schema fails when trying to update codegen

### ISSUE THREAD

**Issue by hanwoollee911** [aws-amplify/amplify-codegen#685]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.18.3

### Amplify CLI Version

12.2.3

### What operating system are you using?

Mac

### Amplify Codegen Command

codegen

### Describe the bug

When I run `amplify codegen` on an environment that already has appsync schema downloaded, the CLi fails with the following message:

```
✖ Downloading schema failed
Could not find the AppSync API. If you have removed the AppSync API in the console run amplify codegen remove
```

However, if I do `amplify codegen remove` and `amplify add codegen --<appId>` it has no problem finding the schema.
I need to apply some flags added to .graphqlconfig.yml so I need to be able to use `amplify codegen`

### Expected behavior

`amplify codegen` updates the existing schema files 

### Reproduction steps

1. `amplify add codegen <appId>`
2. `amplify codegen`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by dpilch** [comment]
Fixed in the latest CLI release.
