### ISSUE TITLE
Amplify codegen fails with error:  "Cannot use 'in' operator to search for 'name' in null"

### ISSUE THREAD

**Issue by ErlendHer** [aws-amplify/amplify-codegen#734]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.17.1

### Amplify CLI Version

12.5.2

### What operating system are you using?

MacOS Sonoma

### Amplify Codegen Command

codegen, codegen types

### Describe the bug

When running `amplify codegen`. We're getting this error: 

`Cannot use 'in' operator to search for 'name' in null`

And `API.ts` fails to generate. However, the `mutations.ts`, `queries.ts` and `subscriptions.ts` all compile.

I'm guessing there is an "in" check somewhere in the code on a null value where an arary / object was expected. That's why we like null-safety and TypeScript <3 (below code produces the same error)
```TypeScript
const iCouldBeNull = null as any;
console.log('name' in iCouldBeNull);
```

Our schema compiles without an error.

This happened after upgrading the CLI from 12.1.1 to 12.5.2.

I tried downgrading the CLI and our schema compiles as expected.

As a side note, when using the CLI 12.5.2, we're also getting errors due to the imports not having `.js` extensions, and since we're using ESM and not CommonJS, this doesn't work for our project and we have to update imports manually with the new version.

### Expected behavior

Amplify codegen should work with a valid schema and provide the correct generated types.

### Reproduction steps

This issue only occurs if there are files in the otuput directory before running amplify codegen.

1. `amplify api gql-compile`
2. `amplify codegen`
3. `amplify codegen`

The third step should fail with the error.

Running the same code with CLI version 12.1.1 (version we used before) works without issues.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ErlendHer** [comment]
So we discovered what is causing the issue, and it's pretty insane I must say.

If there is a SINGLE file in the directory we're generating the types for it will fail with the error above. So the directory must be empty.

Simply clearing the directory (which is annoying cause we have other non-autogenerated files in there) resolves the issue for us.

**Comment by tillschweneker** [comment]
Same here

**Comment by tripproberts** [comment]
I'm seeing this issue as well. I believe the bug was introduced in 12.5.2 as downgrading to 12.5.1 resolves it

**Comment by ErlendHer** [comment]
> I'm seeing the `Cannot use 'in' operator to search for 'name' in null` issue as well. I believe the bug was introduced in 12.5.2 as downgrading to 12.5.1 resolves it

Thanks. Unfortunately we cannot use 12.5.1 as it has bugs related to DataStore for us.

**Comment by pmarkert** [comment]
+1 :)

**Comment by pmarkert** [comment]
The hint above about files in the directory gave me the help to sort through this... I had created an index.ts in the same directory as the generated API files to expose some utility functions. These utility functions were primarily needed before the new type support was added last month (so I could have strongly typed inputs/responses).

**Comment by dpilch** [comment]
I was able to reproduce this. Thanks @pmarkert for the workaround (it lead to finding the root cause quickly). The issue is that the type generation is trying to extract the GraphQL queries from `API.ts`. I'll work on a fix to automatically exclude the `API.ts`.

**Comment by Quix44** [comment]
Big Bump

**Comment by dpilch** [comment]
Please use the `excludes` in `.graphqlconfig.yml` to exclude any files that should not be parsed for GraphQL queries. The error messaging will improve when #738 is released.

**Comment by dpilch** [comment]
Regarding the build failures with ESM, I have opened this issue to track (https://github.com/aws-amplify/amplify-codegen/issues/740). Please comment over there if you have any additional information you would like to share.

**Comment by jgo80** [comment]
For me the workaround did not work, still getting `Cannot use 'in' operator to search for 'name' in null`

**Comment by jgo80** [comment]
> Hi @jgo80, can you provide your `.graphqlconfig.yml` and the contents of your includes pattern?

That's the original:

```yml
projects:
  simplymagic:
    schemaPath: src/graphql/schema.json
    includes:
      - src/graphql/**/*.ts
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: typescript
        generatedFileName: src/API.ts
        docsFilePath: src/graphql
        maxDepth: 2
extensions:
  amplify:
    version: 3
```

the contents of `src/graphql/**/*.ts` are queries and mutations with round about 2000 lines each, it starts with:
```ts
/* tslint:disable */
/* eslint-disable */
// this is an auto generated file. This will be overwritten

import * as APITypes from "../API";
```
... which points to the often referred API.ts

**Comment by dpilch** [comment]
To confirm `src/grapqhl` only contains `mutations.ts`, `queries.ts`, and `subscriptions.ts`?

If you are using an Amplify backend can you run `amplify diagnose` and reply with the ID. https://docs.amplify.aws/cli/reference/diagnose/

If you are not using Amplify can you provide your GraphQL schema.

**Comment by jgo80** [comment]
@dpilch here is what my `src/graphql` contains:
```console
drwxr-xr-x@  7 staff   224B Oct  6 11:44 .
drwxr-xr-x@ 17 staff   544B Oct 20 13:50 ..
-rw-r--r--@  1 staff    53B Oct  6 11:29 index.ts
-rw-r--r--   1 staff    33K Oct 20 15:35 mutations.ts
-rw-r--r--   1 staff    35K Oct 20 15:35 queries.ts
-rw-r--r--   1 staff   839K Oct 20 15:35 schema.json
-rw-r--r--   1 staff    31K Oct 20 15:35 subscriptions.ts
```

I did a diagnose: `Project Identifier: 2e569f8cb3bfc8298fe3eaef4c1bb159`

**Comment by dpilch** [comment]
The `index.ts` is likely causing the error. Adding `- src/graphql/index.ts` to `excludes` in `.graphqlconfig.yml` should fix the issue. https://github.com/aws-amplify/amplify-codegen/pull/738 will allow codegen to continue when encountering this error once it is released. 

I would still recommend adding to the `excludes` for any files that match the `includes` pattern that do not contain GraphQL queries/mutations.

**Comment by jgo80** [comment]
Thank you, sir! 🫡
