### ISSUE TITLE
Codegen and max depth

### ISSUE THREAD

**Issue by bergmorten** [aws-amplify/amplify-codegen#751]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.7.0

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

Codegen and --maxDepth X does not generate the expected code.

First maxDepth is not the depth of relationships but just simple number of recursive object. If you have in the scheme a Type declaration, then these will count as a depth level. 

```graphql
Type Location {
lat: Float!
lon Float!
}

type Car
@model
{
name: String!
location: Location!
}

```

with `amplify codegen --maxDepth 1`

this becomes

```graphql
query GetCar($id: ID!) {
    getCar(id: $id) {
      id
      name
      } 
}
```

Notice that location is missing (Location is not a Model and should have been included)

Next bug is list queries , the object return in items is one depth shallower than in get queries . It would be much more useful if the same data is return in list as in get queries.

with `amplify codegen --maxDepth 1`

```graphql
export const listCars = /* GraphQL */ `query ListCarss(
  $id: ID
  $filter: ModelCarFilterInput
  $limit: Int
  $nextToken: String
  $sortDirection: ModelSortDirection
) {
  listCars(
    id: $id
    filter: $filter
    limit: $limit
    nextToken: $nextToken
    sortDirection: $sortDirection
  ) {
    nextToken
    startedAt
    __typename
  }
}
```

with `amplify codegen --maxDepth 2`

```graphql
query GetCar($id: ID!) {
    getCar(id: $id) {
      id
      name
      location // <--- location is now included with depth 2
      } 
}

export const listCars = /* GraphQL */ `query ListCarss(
  $id: ID
  $filter: ModelCarFilterInput
  $limit: Int
  $nextToken: String
  $sortDirection: ModelSortDirection
) {
  listCars(
    id: $id
    filter: $filter
    limit: $limit
    nextToken: $nextToken
    sortDirection: $sortDirection
  ) {
    items {  // <--- Location is not included
      id
      name 
    }
    nextToken
    startedAt
    __typename
  }
}
```
 

### Expected behavior

1. None model type should not count in depth (only relations or sub queries counts)

2. List queries should count items as a depth level. Entries in items should be equal to a get query.

### Reproduction steps

1. make a scheme type that is not a model and reference that in a model type
2. Generate models with maxDepth 1 vs 2
3. Observe that they are different
4. List queries are useless at maxDepth 1, and items return is always one level shallower that get queries.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by phani-srikar** [comment]
Hi @bergmorten, thanks for pointing out these differences. The reason `list` queries are one level shallower than `get` is because of the additional `items` key in the response. As per the behavior for non-model types, it's because there is no utility in including those without any of their fields, hence they're skipped until the `maxDepth` setting allows us to generate their sub fields as well.

**Comment by bergmorten** [comment]
I strongly disagree with this since both is obvious an error or lazy work. We expect that the model/object return for a get or list should be equal.  And your dcumentation on the web page of maxt depth (  https://docs.amplify.aws/cli/graphql/client-code-generation/#statement-depth ), and talks about connections and there is no explanation that List have one depth shallower or non-connected models counts.

_In the below schema there are **connections** between Comment -> Post -> Blog -> Post -> Comments. When generating statements codegen has a default limit of 2 for depth traversal. But if you need to go deeper than 2 levels you can change the maxDepth parameter either when setting up your codegen or by passing --maxDepth parameter to codegen_

# fix 
It should be easy to include a logic in your  generator that increase max depth by one if it is a `list query`.

For non connecting model you do manage to  generate information that this is not a connecting model. E.g. under models/schema.js

```javascript 
   "location": {
                    "name": "location",
                    "isArray": false,
                    "type": {
                        "nonModel": "Location" // <-- See this has parameter nonModel, if is was a connected model it would have been "model"
                    },
                    "isRequired": false,
                    "attributes": []
                },
````

Obviously you do have the logic to determine if a model is a connected model or non-connected model.  And it should be very easy to have logic in the generator to not count non-connected models against the max depth.

Currently we must use the generator with two more depth in max level. Then have a script with a really messy reg exp to remove the extra two depth for get queries , one one depth for list queries, and a logic for non-connected models.
