### ISSUE TITLE
Missing Types

### ISSUE THREAD

**Issue by thomasdavidwang** [aws-amplify/amplify-codegen#775]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.17.0

### Amplify CLI Version

12.10.0

### What operating system are you using?

Mac

### Amplify Codegen Command

codegen models

### Describe the bug

After generating, receiving the following type errors in all <model>+Schema.swift files: 
- Type 'ModelAttribute' has no member 'primaryKey'
- Cannot find type 'ModelIdentifiable' in scope
- Cannot find type 'ModelIdentifierFormat' in scope
- Cannot find type 'DefaultModelIdentifier' in scope

### Expected behavior

No errors. 

### Reproduction steps

1. amplify codegen models

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by dpilch** [comment]
Hi @thomasdavidwang, I wasn't able to reproduce this issue. Have you followed the instructions to add the Amplify package to your project? https://docs.amplify.aws/swift/start/getting-started/setup/#add-amplify-to-your-application

**Comment by phani-srikar** [comment]
Please re-open if this issue still exists.
