### ISSUE TITLE
Allow saving patch changes to generated code  

### ISSUE THREAD

**Issue by Eliav2** [aws-amplify/amplify-codegen#781]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.16.1

### Amplify CLI Version

12.10.0

### What operating system are you using?

windows

### Amplify Codegen Command

codegen

### Describe the bug

not, a bug. feature request.

### Expected behavior

I'm using aws cli codegen quite a lot and it's saving me quite time. 

however, sometimes i make changes to ui components inside the ui-components folder, changes that must be made from within the generated ui component. it could have been awesome to provide a mechanism that allows to save and apply my own patches to the ui component, similar to how [patch-package](https://www.npmjs.com/package/patch-package) allowing patching node_modules directory in a predictable way. such feature is must have in my opinion and allow users to not opting-out of the generated code, saving time, and money.

### Reproduction steps

.

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Additional information

.

**Comment by Eliav2** [comment]
is it actually possible using [amplify hooks](https://docs.amplify.aws/react/tools/cli/project/command-hooks/).

create git patches to the file you want to override, save them in some directory. in my case i saved them in `src/patches/`. then create an `post-push` hook:
```sh
# amplify/hooks/post-push.sh
echo executing post-push hook
echo applying patches saved in src/patches
git apply src/patches/*.patch
```

now the changes are restored correctly after each push. you might as well want to create patches to other commands such `post-pull`.

**Comment by phani-srikar** [comment]
Thanks for this request @Eliav2. Since you're able to achieve this using CLI command hooks, I will go ahead and close this.
