### ISSUE TITLE
Angular code generation for v6 amplify

### ISSUE THREAD

**Issue by qwe12e** [aws-amplify/amplify-codegen#783]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v18.12.1

### Amplify CLI Version

12.10.1

### What operating system are you using?

Mac

### Amplify Codegen Command

codegen types

### Describe the bug

I'm following the tutorials in here [amplify](https://docs.amplify.aws/angular/build-a-backend/graphqlapi/mutate-data/). I'm trying to generate api.service.ts using `amplify codegen types`. But this package is creating older version of amplify what I mean is that it is trying to import 
```ts
import API, { graphqlOperation, GraphQLResult } from "@aws-amplify/api-graphql";
import { Observable } from "zen-observable-ts";
```
but it should do something like this: 

```ts
import { generateClient } from 'aws-amplify/api';
import * as mutations from './graphql/mutations';

const client = generateClient();

const updatedTodo = await client.graphql({
  query: mutations.updateTodo,
  variables: { input: {} }
});
```

### Expected behavior

it should create the new way of sending requests in the service.

### Reproduction steps

run `amplify codegen types`

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by jkeczan** [comment]
I am seeing the same. I am upgrading to V6

**Comment by mohammedsahl** [comment]
Likewise. Also upgrading to v6. We're pretty dependant on codegen. Doing this manually would be some work 😰

**Comment by hisham** [comment]
+1. Is this going to be done anytime soon? Seems like it should be high priority, but I see it's not even assigned to anybody at this point.

**Comment by david-mcafee** [comment]
@qwe12e - thank you for filing this issue! We are currently investigating a fix, and will update when we have more information.

**Comment by qwe12e** [comment]
If anyone interested for a quick fix in my project I did this:


```ts

import { Injectable } from '@angular/core';
import { GraphQLResult } from '@aws-amplify/api-graphql';
import { Observable } from 'rxjs';
import { generateClient } from 'aws-amplify/api';
const client = generateClient();
const graphqlOperation = (statement: string, args = {}) => {
  return {
    query: statement,
    variables: args,
  };
};

const API = {
  graphql: ({ query, variables = {} }: { query: string; variables: Object }) => {
    return client.graphql({ query, variables });
  },
};
```
<img width="1389" alt="image" src="https://github.com/aws-amplify/amplify-codegen/assets/13543079/e2cd404f-fe05-4608-b719-1839befa52bb">
if you write post before your script it means that it will run after that script so in this case

I'm calling `npm run codegen` after this finishes npm will automatically run the postcodegen script.

In this script I just do find and replace

```ts
const path = require('path');
const replace = require('replace-in-file');

// path to the GQL Service
const servicePath = path.resolve(__dirname, '..', 'src', 'app', 'services', 'gql.service.ts');

async function replaceFile() {
  try {
    // add the custom API and graphqlOperation
    await replace({
      files: servicePath,
      from: /api-graphql';/,
      to: `api-graphql';
    import { Observable } from 'rxjs';
    import { generateClient } from 'aws-amplify/api';
    const client = generateClient();
    const graphqlOperation = (statement: string, args = {}) => {
      return {
        query: statement,
        variables: args,
      };
    };

    const API = {
      graphql: ({ query, variables = {} }: { query: string; variables: Object }) => {
        return client.graphql({ query, variables });
      },
    };
      `,
    });
  } catch (error) {
      console.error('Error occurred:', error);
    }
 }

replaceFile();
```

this way I don't need to worry about the generated methods. It will use the newer functions
