### ISSUE TITLE
Using codegen model - Flutter

### ISSUE THREAD

**Issue by rlee1990** [aws-amplify/amplify-codegen#83]
When using codegen model any types without a @model do not get generated.

**Comment by kjones** [comment]
Related: https://github.com/aws-amplify/amplify-flutter/issues/260

**Comment by rlee1990** [comment]
@kjones thanks closing this one then

**Comment by kjones** [comment]
@rlee1990 - Since you're closing this I would say give that related issue a 👍🏻 and perhaps also add a quick comment.
