### ISSUE TITLE
Unable to generate operations.graphql

### ISSUE THREAD

**Issue by charlieforward9** [aws-amplify/amplify-codegen#838]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-codegen/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-codegen/blob/main/CONTRIBUTING.md#bugs).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

20.9.0

### Amplify CLI Version

12.11.1

### What operating system are you using?

Mac

### Amplify Codegen Command

other `codegen <subcommand>` (please mention in the issue)

### Describe the bug

I would like to efficiently generate RTK Query hooks for my Amplify application using [this tool](https://the-guild.dev/graphql/codegen).

I have not been able to figure out how to generate the code that belongs in the `operations.graphql` input. In other word, the files that are generated with `amplify codegen statements` but without the Typescript wrapped around. 

<img width="1424" alt="Screenshot 2024-05-06 at 11 20 39 PM" src="https://github.com/aws-amplify/amplify-codegen/assets/62311337/4306fa09-c316-417b-9bc2-1768f3f4f295">

Maybe I am missing a simple command, but if not it would be really helpful to have this as a codegen statement...

### Expected behavior
<img width="141" alt="Screenshot 2024-05-06 at 11 56 26 PM" src="https://github.com/aws-amplify/amplify-codegen/assets/62311337/ad02ff96-9d4f-4801-bd29-3965f2d54a73">

The output I expect is the `useGetAccountQuery`, but properly typed with the queries definition found in `graphql/queries.ts`, but without the typescript wrapping it.

<img width="538" alt="Screenshot 2024-05-06 at 11 25 31 PM" src="https://github.com/aws-amplify/amplify-codegen/assets/62311337/1aa8d87c-a4b1-497d-a157-e542551c23a2">

I would like to have an option to access these statements in their graphql syntax within my codebase via this codegen package.

### Reproduction steps

1. Install this lib
2. Try to get a single `graphql` file with all of the operations the schema offers.

**Comment by dpilch** [comment]
Changing your `codeGenTarget` to `graphql` in `.graphqlconfig.yml` will generate the GraphQL statements in raw GraphQL syntax.

```
projects:
  Codegen Project:
    extensions:
      amplify:
        codeGenTarget: graphql
```

**Comment by charlieforward9** [comment]
Thank you - this solved my problem. 


This would be nice to have as a CLI config, or specified somewhere in docs. 

Maybe I missed it. Thank you.

**Comment by charlieforward9** [comment]
@dpilch Is there a plan to support this with `amplify mock api`?

**Comment by dpilch** [comment]
That is not prioritized at this time.
