### ISSUE TITLE
how to fix graphql query can't get full result?

### ISSUE THREAD

**Issue by ipsonkat** [aws-amplify/amplify-codegen#849]
when i added @searchable to a table in schema the list query will not work probably. when i use List query Photos by filtering photosCaseHistoryId, then i only get 1 record for the result but the result actually should has 2 records, and I have no set limit in query.

my schema:
type CaseHistories @model @auth(rules: [{allow: public}]) @searchable{
  id: ID!
  User: Users @hasOne
  remark: String
  Case: Cases @hasOne
  Location: Locations @hasOne
  title: String
}

type Photos @model @auth(rules: [{allow: public}]) {
  id: ID!
  key: String!
  createdOn: AWSDateTime
  updatedOn: AWSDateTime
  CaseHistory: CaseHistories @hasOne
}

**Comment by AnilMaktala** [comment]
Hey 👋 , This issue is being closed due to inactivity. If you are still experiencing the same problem and need further assistance, please feel free to leave a comment. This will enable us to reopen the issue and provide you with the necessary support.
