### ISSUE TITLE
Swift Code Generator Produces Incorrect Syntax for `hasMany` Relationship

### ISSUE THREAD

**Issue by espenbye** [aws-amplify/amplify-codegen#867]
### Environment information

```plain text
System:
  OS: macOS 15.1
  CPU: (12) arm64 Apple M2 Pro
  Memory: 159.19 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 20.9.0 - ~/.nvm/versions/node/v20.9.0/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v20.9.0/bin/yarn
  npm: 10.1.0 - ~/.nvm/versions/node/v20.9.0/bin/npm
  pnpm: 8.8.0 - ~/.nvm/versions/node/v20.9.0/bin/pnpm
NPM Packages:
  @aws-amplify/backend: 1.0.0
  @aws-amplify/backend-cli: 1.0.1
  aws-amplify: 6.3.6
  aws-cdk: Not Found
  aws-cdk-lib: Not Found
  typescript: 5.4.5
AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
No CDK environment variables
```

### Description

The code generator is producing Swift code with incorrect syntax for the `hasMany` relationship. Specifically, it's missing a closing parenthesis at the end of the `hasMany` field definition. This syntax error prevents the code from compiling correctly.

Steps to Reproduce:
1. Use the code generator to create Swift code for a model with a `hasMany` relationship.
2. Observe the generated code for the `hasMany` field.

Expected Result:
The `hasMany` field should have a closing parenthesis after the `associatedFields` parameter.

Actual Result:
The generated code is missing the closing parenthesis, causing a syntax error.

Example of Incorrect Generated Code:
```swift
.hasMany(consent.memberConsents, is: .optional, ofType: MemberConsent.self, associatedFields: [MemberConsent.keys.consent],
```

Correct Code:
```swift
.hasMany(consent.memberConsents, is: .optional, ofType: MemberConsent.self, associatedFields: [MemberConsent.keys.consent]),
```

**Comment by mertkarahan955** [comment]
`const schema = a.schema({
  Todo: a
    .model({
      title: a.string().required(),
      content: a.string().required(),
      isDone: a.boolean(),
   
      todoListId: a.id(),
        todoList: a.belongsTo('TodoList', 'todoListId'),
    })
    .authorization((allow) => [allow.owner()]),
  TodoList: a.model({
     name: a.string().required(),
     // hasMany relationship with the reference field from Todo Model
     members: a.hasMany('Todo', 'todoListId')
  }).authorization((allow) => [allow.owner()]),
});
export type Schema = ClientSchema<typeof schema>;
export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: 'userPool',
  },
});`

Here is my schema. When I run this command: 
npx ampx generate graphql-client-code --format modelgen --model-target dart --out lib/models 
it does not generate me the todoListId. and when I try to create todo, I am getting this error: 

` GraphQLResponse<Todo>: {
  "data": {
    "id": "0f978bb0-d387-4cec-90a2-1100106d9c55",
    "title": "my todo",
    "content": "Content of Todo",
    "isDone": false,
    "isShared": null,
    "todoList": null,
    "createdAt": "2024-08-20T21:15:38.677000000Z",
    "updatedAt": "2024-08-20T21:15:38.677000000Z"
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable type: 'ID' within parent 'TodoList' (/createTodo/todoList/id)",
      "path": [
        "createTodo",
        "todoList",
        "id"
      ]
    },
    {
      "message": "Cannot return null for non-nullable type: 'String' within parent 'TodoList' (/createTodo/todoList/name)",
      "path": [
        "createTodo",
        "todoList",
        "name"
      ]
    },
    {
      "message": "Cannot return null for non-nullable type: 'AWSDateTime' within parent 'TodoList' (/createTodo/todoList/createdAt)",
      "path": [
        "createTodo",
        "todoList",
        "createdAt"
      ]
    },
    {
   <…>
flutter: Creating Todo failed.`

**Comment by mertkarahan955** [comment]
`
const schema = a.schema({
  Todo: a
    .model({
      title: a.string().required(),
      content: a.string().required(),
      isDone: a.boolean(),
   
      todoListId: a.id(),
        todoList: a.belongsTo('TodoList', 'todoListId'),
    })
    .authorization((allow) => [allow.owner()]),
  TodoList: a.model({
     name: a.string().required(),
     // hasMany relationship with the reference field from Todo Model
     members: a.hasMany('Todo', 'todoListId')
  }).authorization((allow) => [allow.owner()]),
});
export type Schema = ClientSchema<typeof schema>;
export const data = defineData({
  schema,
  authorizationModes: {
    defaultAuthorizationMode: 'userPool',
  },
});
`
Here is my schema. When I run this command: 
npx ampx generate graphql-client-code --format modelgen --model-target dart --out lib/models 
it does not generate me the todoListId. and when I try to create todo, I am getting this error: 
`
 GraphQLResponse<Todo>: {
  "data": {
    "id": "0f978bb0-d387-4cec-90a2-1100106d9c55",
    "title": "my todo",
    "content": "Content of Todo",
    "isDone": false,
    "isShared": null,
    "todoList": null,
    "createdAt": "2024-08-20T21:15:38.677000000Z",
    "updatedAt": "2024-08-20T21:15:38.677000000Z"
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable type: 'ID' within parent 'TodoList' (/createTodo/todoList/id)",
      "path": [
        "createTodo",
        "todoList",
        "id"
      ]
    },
    {
      "message": "Cannot return null for non-nullable type: 'String' within parent 'TodoList' (/createTodo/todoList/name)",
      "path": [
        "createTodo",
        "todoList",
        "name"
      ]
    },
    {
      "message": "Cannot return null for non-nullable type: 'AWSDateTime' within parent 'TodoList' (/createTodo/todoList/createdAt)",
      "path": [
        "createTodo",
        "todoList",
        "createdAt"
      ]
    },
    {
   <…>
flutter: Creating Todo failed.
`

**Comment by dpilch** [comment]
This was fixed with https://github.com/aws-amplify/amplify-codegen/pull/835. Please use `npm upgrade` to pull the latest version.
